### ISSUE TITLE
怎么知道一个群聊是否可以聊天

### ISSUE THREAD

**Issue by snowman** [lich0821/WeChatFerry#114]
比如:
- 当被群主/管理员移出群聊
- 主动退群
- 群聊违规, 被举报投诉停用
- 群聊被解散

**Comment by lich0821** [comment]
也许通过数据库查询可以实现。

**Comment by wangtu** [comment]
SELECT
                                        UserName,
                                        Remark,
                                        NickName
                                    FROM
                                        Contact t1
                                    WHERE
                                        t1.Type = 2
                                        and t1.DelFlag = 0
