### ISSUE TITLE
希望增加一个根据wxid添加好友的功能，

### ISSUE THREAD

**Issue by taozi926494** [lich0821/WeChatFerry#117]
**你希望添加的功能是否与某个问题相关？**
在接收到群消息的时候，一些比较感兴趣的话题，希望添加这个人为好友。看到其他类似的项目具备此功能

**描述你希望的解决方案**
传入wxid，添加好友

**Comment by lich0821** [comment]
怕不是想爆粉吧😂

**Comment by taozi926494** [comment]
不是的，就是业务上纯粹是有这个需求

**Comment by limcod** [comment]
这个有开发计划吗

**Comment by rehiy** [comment]
可能会爆号

**Comment by limcod** [comment]
爆号是什么意思

**Comment by sasicDHH** [comment]
既然无法自动通过，可以曲线救国加回去嘛？？？ @lich0821
