### ISSUE TITLE
[🐛BUG] download_attach无法下载图片

### ISSUE THREAD

**Issue by Sakura3333** [lich0821/WeChatFerry#119]
当我接收到图片消息时，执行download_attach下载图片，得到的是空字符串，前几天还好好的，从昨天开始就没用了，重启微信删除lock文件都没用

- 操作系统：Windows 10
- 操作系统版本：64 位
- Python 版本：3.11

![微信截图_20240119145645](https://github.com/lich0821/WeChatFerry/assets/71971452/1baaa0ef-a6d3-43ff-b24b-bfa740228847)

**Comment by lich0821** [comment]
won't fix.

**Comment by Sakura3333** [comment]
> won't fix.

有其它替代方法吗

**Comment by lich0821** [comment]
> > won't fix.
> 
> 有其它替代方法吗

[download_image](https://wechatferry.readthedocs.io/zh/latest/autoapi/wcferry/client/index.html#wcferry.client.Wcf.download_image)

**Comment by Sakura3333** [comment]
> > > won't fix.
> > 
> > 
> > 有其它替代方法吗
> 
> [download_image](https://wechatferry.readthedocs.io/zh/latest/autoapi/wcferry/client/index.html#wcferry.client.Wcf.download_image)

Thanks！
