### ISSUE TITLE
HTTP API有时候会只接收到一个请求头，没有消息内容

### ISSUE THREAD

**Issue by Yumengming0708** [lich0821/WeChatFerry#124]
使用HTTP API，Java监听接收消息时候只能收到请求头，请求体会被单独作为一个请求发送，并且两个请求中间间隔很长。
![1706544655894](https://github.com/lich0821/WeChatFerry/assets/138636524/732ae34d-4d88-413f-9d07-20f9696274b0)
![fca4a8e60a95512b1d8c8686d6de9f7](https://github.com/lich0821/WeChatFerry/assets/138636524/a4e3bae8-bc1d-41e8-b120-f6f333100756)
另外，后台中每转发一个消息都会提示消息转发异常，无论后端是否正常接收到整个请求
![1706544888653](https://github.com/lich0821/WeChatFerry/assets/138636524/90b44870-b45c-45ea-acb0-d79d2997205a)

**Comment by lich0821** [comment]
建议先了解一下HTTP，以及如何在Java中实现一个HTTP服务。
