### ISSUE TITLE
[🐛BUG] Wcf.download_image 下载超时

### ISSUE THREAD

**Issue by winniesi** [lich0821/WeChatFerry#125]
**描述这个 bug**
python 版本遇到一个问题，Wcf.download_image 下载图片会出现「下载失败」或「下载超时」错误，似乎 download_attach 和 decrypt_image 两个方法都可能出错。

```
def process_msg(self, msg: WxMsg) -> None:
    if msg.type == 3:
        wcf.download_image(msg.id, msg.extra, "current_path_str")
```

请求之前 msg.id 和 msg.extra 都已经识别出来了

msg.id：`3024853163291771447`

msg.extra：`C:/Users/winniesi/Documents/WeChat Files/wxid_uu35q29y8d8y22/FileStorage/MsgAttach/9c4414cfa1ab5d15075b830110efa8e8/Image/2024-02/c546ef3b97f1e929c167c4db02a1fb17.dat`

**使用环境:**
- 操作系统：windows 11
- 操作系统版本：ARM 版本
- Python 版本：3.9 32位版本

**Comment by WyntersN** [comment]
怎么下载好的，我也超时了
