### ISSUE TITLE
【封号】吃瓜，一起看热闹

### ISSUE THREAD

**Issue by xzy103** [lich0821/WeChatFerry#126]
![f75e8632bf85dfb98a84c0aaa4d3810f](https://github.com/lich0821/WeChatFerry/assets/40889019/6ce6ffb7-4135-4db2-9a6d-5bfa11e2d6b3)
用自己的小号搞的，http方案，接入了ChatGPT，加到了几个群里，@并提问就可以获得gpt响应。

运行了一段时间，突然就被提示违规了，小号违规也就罢了，还连带把我完全没参与的大号也给封了（妈呀）

大号让我签保证书才给我解封的，小号也是让我验证后才给解封的。

**总之，大家悠着点吧。**

**Comment by Cherrysaber** [comment]
小号别实名认证，实名认证的，所有实名一样的全部端了

**Comment by xzy103** [comment]
> 小号别实名认证，实名认证的，所有实名一样的全部端了

多谢提醒，虽然已经晚了 T_T
不过微信一定要用手机号才能注册，如果是自己名下的手机号，理论上也能一锅端。

**Comment by RicardoJackMC** [comment]
刚刚被封😂
电脑端突然下线，尝试重新登录，才发现被封😂
用的是 python 客户端，然后用了 pywinauto 实现登录的时候自动评论自己的朋友圈（用来通知别人）
有没有可能是因为挂太久被发现异常（电脑差不多开了两周然后一直登着微信）

**Comment by xzy103** [comment]
> 刚刚被封😂 电脑端突然下线，尝试重新登录，才发现被封😂 用的是 python 客户端，然后用了 pywinauto 实现登录的时候自动评论自己的朋友圈（用来通知别人） 有没有可能是因为挂太久被发现异常（电脑差不多开了两周然后一直登着微信）

对，我也是一直挂机，挂了两周，7 x 24

**Comment by xzy103** [comment]
> 刚刚被封😂 电脑端突然下线，尝试重新登录，才发现被封😂 用的是 python 客户端，然后用了 pywinauto 实现登录的时候自动评论自己的朋友圈（用来通知别人） 有没有可能是因为挂太久被发现异常（电脑差不多开了两周然后一直登着微信）

对，我也是一直挂机，挂了两周，7 x 24

**Comment by Cherrysaber** [comment]
> > 刚刚被封😂 电脑端突然下线，尝试重新登录，才发现被封😂 用的是 python 客户端，然后用了 pywinauto 实现登录的时候自动评论自己的朋友圈（用来通知别人） 有没有可能是因为挂太久被发现异常（电脑差不多开了两周然后一直登着微信）
> 
> 对，我也是一直挂机，挂了两周，7 x 24

我就1月16号-1月19号接了个GPT，在群里和朋友玩，之后就没用过了。然后在2月2号把我封了

**Comment by stkevintan** [comment]
被警告了 +1

**Comment by fjc0k** [comment]
+1，我就单纯挂着也给封了

**Comment by lich0821** [comment]
[微信机器人被封号？记住这些注意事项](https://mp.weixin.qq.com/s/ZFQ5ZBWV4uYAeWO6-qsbUA)，留言更精彩。

**Comment by yangweijie** [comment]
> 小号别实名认证，实名认证的，所有实名一样的全部端了

不实名没法被邀请加入群聊

**Comment by atorber** [comment]
> [微信机器人被封号？记住这些注意事项](https://mp.weixin.qq.com/s/ZFQ5ZBWV4uYAeWO6-qsbUA)，留言更精彩。

微信异常行为探讨：https://www.yuque.com/atorber/chatflow/eydtegkpf1ww6m2g

**Comment by alex-oos** [comment]
啊，这么严重的么？

**Comment by pingxingshikong** [comment]
看下这个稳如老狗  https://o6bnu3uipp.apifox.cn

**Comment by muccccc** [comment]
> 有个办法不会被封号，我分享一下：`不使用微信` 😂

大佬有被封控过吗，csdn上说这个框架比较稳定，我还没开始用

**Comment by MHK-MHK** [comment]
+1，昨天被警告了

**Comment by GeekWorkCode** [comment]
+1 今天被警告了

**Comment by jiyi** [comment]
+1 今天被警告了

**Comment by walterFeng** [comment]
今天被封号7天，但是是上一个版本，有人用过最新版封号吗？

**Comment by HyhBlazing** [comment]
+1 7天

**Comment by treehairs** [comment]
有没有大佬知道被封7天后要养多久号，下次再开才不会被封。或者下次被封会被封多久😬
前天被警告，昨天开了一下然后就关掉，结果隔两三个小时就被封7天😂

**Comment by HyhBlazing** [comment]
> 有没有大佬知道被封7天后要养多久号，下次再开才不会被封。或者下次被封会被封多久😬 前天被警告，昨天开了一下然后就关掉，结果隔两三个小时就被封7天😂

一模一样

**Comment by ZP0505** [comment]
+1 被封，验证后解封  用的还是老版本 新版本不知道你们封了没

**Comment by MemoryCollection** [comment]
> ![f75e8632bf85dfb98a84c0aaa4d3810f](https://github.com/lich0821/WeChatFerry/assets/40889019/6ce6ffb7-4135-4db2-9a6d-5bfa11e2d6b3) 用自己的小号搞的，http方案，接入了ChatGPT，加到了几个群里，@并提问就可以获得gpt响应。
> 
> 运行了一段时间，突然就被提示违规了，小号违规也就罢了，还连带把我完全没参与的大号也给封了（妈呀）
> 
> 大号让我签保证书才给我解封的，小号也是让我验证后才给解封的。
> 
> **总之，大家悠着点吧。**

是同一人实名 吗？

**Comment by NightMingGit** [comment]
7天

**Comment by biechuyangwang** [comment]
封的早的好处，我快出来了

**Comment by pascals-law** [comment]
+1 封了7天，明天才出来

**Comment by pascals-law** [comment]
+1 用的新版接了ds，问了俩问题后被封了7天，明天才出来。

**Comment by lich0821** [comment]
> +1 用的新版接了ds，问了俩问题后被封了7天，明天才出来。

今晚发个版，明天继续😬

**Comment by HyhBlazing** [comment]
> 不用gpt会不会封号呢？只转发文章

依旧会，只要开启。 不管你怎么用，

**Comment by ZippoLee12138** [comment]
> 刚刚被封😂 电脑端突然下线，尝试重新登录，才发现被封😂 用的是 python 客户端，然后用了 pywinauto 实现登录的时候自动评论自己的朋友圈（用来通知别人） 有没有可能是因为挂太久被发现异常（电脑差不多开了两周然后一直登着微信）
我正想试一下这个方法呢

**Comment by HyhBlazing** [comment]
我是一直一直都挂着，不用其他任何脚本的情况下，只正常登录，几年了，一直登录没有出现过问题，用了就出现了，。




Blazing______
***@***.***
