### ISSUE TITLE
[💡SUG] 消息回调中增加发送者的昵称

### ISSUE THREAD

**Issue by x7yue** [lich0821/WeChatFerry#130]
在收到群聊消息想艾特别人，一般都会 `@昵称 xxxxx` 目前回调消息中无发送者昵称字段，且似乎没有其他办法获得。
而且我在测试随便填写 `@xxx` 的时候，手机上并没有对应的艾特提示。只有写对昵称才会有提示。
希望能增加这个字段，谢谢

**Comment by lich0821** [comment]
提示应该只跟 `wxid` 有关；办法是通过 `SQL` 查询，或者使用 [get_alias_in_chatroom](https://github.com/lich0821/WeChatFerry/blob/master/clients/python/wcferry/client.py#L929)

**Comment by x7yue** [comment]
> 提示应该只跟 `wxid` 有关；办法是通过 `SQL` 查询，或者使用 [get_alias_in_chatroom](https://github.com/lich0821/WeChatFerry/blob/master/clients/python/wcferry/client.py#L929)

谢了，我先用这个办法解决一下。还是希望能直接回调比较方便QAQ
