### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by wangtu** [lich0821/WeChatFerry#133]
- 什么问题？
-功能清单中-forward_msg 转发只支持文本、xml。不支持图片和语音。调用无任何效果

- 是否安装后第一次启动就出现？
- 是，最新sdk
- 

**使用环境（请补全下列信息）:**
- 操作系统：【Windows 10】
- 操作系统版本：【64 位】
- Python 版本：【如 3.7.9 32 】

**Comment by lich0821** [comment]
帮你 @微信

**Comment by QB-Chen** [comment]
+1，我怎么也转发不了，显示转发成功了，但是实际上并没有转发，我print输出出来是个xml格式的文本
