### ISSUE TITLE
私聊时报错 提示openai 版本问题

### ISSUE THREAD

**Issue by qujunde** [lich0821/WeChatFerry#134]
第一次部署
运行一切正常，私聊有人私聊得时候就会报错
![微信截图_20240317175731](https://github.com/lich0821/WeChatFerry/assets/6947476/e214743b-4935-47de-aeb5-77bc70548327)
我尝试换了OPENAI版本0.28 然后无法运行 ，换回openai高版本 可以运行 私聊问题重现
配置文件 没有配置任意机器人 不知道是否与这个有关，我不需要AI功能。

[Uploading wx_info.log…]()

**Comment by lich0821** [comment]
这不是WeChatFerry的问题，提到Robot那边吧。
