### ISSUE TITLE
[💡SUG] java客户端不维护吗

### ISSUE THREAD

**Issue by ibalbal** [lich0821/WeChatFerry#135]

**Comment by lich0821** [comment]
维护不过来了。用HTTP客户端吧。
### HTTP
#### [wcfrust](https://github.com/lich0821/wcf-client-rust)（基于 Rust）
开箱即用：[快速开始](https://github.com/lich0821/wcf-client-rust?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)。

#### GoHttp（基于 Go）
参考 [GoHttp README.MD](clients/gohttp/README.md)
