### ISSUE TITLE
[🐛BUG] Server disconnected without sending a response.

### ISSUE THREAD

**Issue by PigsyAK** [lich0821/WeChatFerry#136]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
  - 客户端（机器人框架改造）运行一段时间就好接收不到微信信息了，像是卡住了一样。
  - 但是好像一直聊天就没问题，就是长时间（10分钟往上）没有微信信息后会卡住，无法再接收信息了，需要重启客户端。
- 是否安装后第一次启动就出现？
  - 否
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
  - 不用重启微信，客户端重启连接即可。
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？ 
  - 正常

**使用环境（请补全下列信息）:**
- 操作系统：【Windows 11, Ubuntu22.04】
- 操作系统版本：【64 位】
- Python 版本：【3.11.6】

```shell
[tool.poetry.dependencies]
python = "^3.10"
wcferry = "^39.0.14.1"
pyyaml = "^6.0.1"
google-generativeai = "^0.4.1"
openai = "^1.14.1"
zhipuai = "^2.0.1"
pandas = "^2.2.1"
lxml = "^5.1.0"
chinese-calendar = "^1.9.1"
sparkdesk-api = "^1.5.0"
zhdate = "^0.1"
pillow = "^10.2.0"
jupyter-client = "^8.6.1"
websocket = "^0.2.1"
pyhandytools = "^0.1.3"
numpy = "^1.26.4"
apscheduler = "^3.10.4"
```

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![image](https://github.com/lich0821/WeChatFerry/assets/122603246/b3402ef4-d836-4090-85ee-735c15d68d12)

```shell
2024-03-20 09:13:52,281 WCF ERROR client.py::__init__[92]:连接失败: no link
2024-03-21 09:36:26,970 Robot ERROR robot.py::innerProcessMsg[200]:Receiving message error: Server disconnected without sending a response.
```

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
未改造前也有同样的问题吗？

**Comment by PigsyAK** [comment]
没测过，但说是改造，其实核心没有动过的，就是任务调度换了apschedule，但是我不启动定时任务也是如此

**Comment by PigsyAK** [comment]
中午起来发现：
2024-03-21 14:16:34 Receiving message error: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

另外，我的服务端和客户端是分开部署的

**Comment by PigsyAK** [comment]
服务端在Windows server 2012 R2，客户端是Windows11

**Comment by G3G4X5X6** [comment]
windows server 2016 + ubuntu22.04长时间不处理消息后，接收不了信息，ctrl + c后报错：
2024-03-21 19:06:29,864 WCF ERROR client.py::logerror[32]:Call FUNC_DISABLE_RECV_TXT failed: Timed out

**Comment by lich0821** [comment]
复现不了你的问题。你直接用 HTTP 客户端吧。

**Comment by G3G4X5X6** [comment]
好嘞
