### ISSUE TITLE
[💡SUG] 新增 token 认证通信的选项

### ISSUE THREAD

**Issue by PigsyAK** [lich0821/WeChatFerry#137]
**你希望添加的功能是否与某个问题相关？**
我的使用场景是服务端和客户端是分开部署的，但是直接host+port就可以访问控制微信，不安全。

**描述你希望的解决方案**
所以，希望可以新增一个 token 认证通信的选项

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by lich0821** [comment]
Duplicated with #86
