### ISSUE TITLE
[🐛BUG] 在群里发送text消息，并不能@人

### ISSUE THREAD

**Issue by mggzhu** [lich0821/WeChatFerry#138]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
- 是否安装后第一次启动就出现？
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？

**使用环境（请补全下列信息）:**
- 操作系统：windows
- 操作系统版本：win64
- Python 版本：Python 3.12.1 

**屏幕截图**
![image](https://github.com/lich0821/WeChatFerry/assets/154853194/d6029b87-a3ac-4083-8947-f1740d92a754)

**崩溃信息**

**Comment by lich0821** [comment]
请读文档。
