### ISSUE TITLE
iphone手机发送的视频调用download_attach方法 无法下载成功

### ISSUE THREAD

**Issue by haha1421** [lich0821/WeChatFerry#139]
通过测试发现，当发送mov格式的视频文件 或者直接 用苹果手机录制一个短视频发送到群里，当调用wcf.download_attach(id, thumb, extra) 下载这个mov视频文件 无法下载成功

没法大佬看看什么原因，能否修复这个问题

**Comment by lich0821** [comment]
请参考报BUG模板提供必要信息。
