### ISSUE TITLE
[💡SUG] 接收的图片、语音存至本地

### ISSUE THREAD

**Issue by haofanurusai** [lich0821/WeChatFerry#14]
**你希望添加的功能是否与某个问题相关？**
能收到图片和语音数据并正常打印，但是不知这串数据如何利用？

**描述你希望的解决方案**
是否可以考虑提供类似接口或解密手段
```
    msg.is_pic() -> Bool
    msg.is_voice() -> Bool
    msg.get_pic(encode='base64') ->str
    msg.get_voice(encode='base64') ->str
    msg.save_pic(path='./1.jpg')
    msg.save_voice(path='./1.amr')
```

**Comment by lich0821** [comment]
图片解密已实现：[decrypt_image](https://github.com/lich0821/WeChatFerry/blob/d17e2e47378580efb4eccf775fb49c83a1f983dd/python/wcferry/client.py#L440)

**Comment by Jkanon** [comment]
> 图片解密已实现：[decrypt_image](https://github.com/lich0821/WeChatFerry/blob/d17e2e47378580efb4eccf775fb49c83a1f983dd/python/wcferry/client.py#L440)

请问如何获取图片的保存路径，图片消息里只有原始cdn加密信息？谢谢

**Comment by lich0821** [comment]
见 [WxMsg](https://github.com/lich0821/WeChatFerry/blob/master/clients/python/wcferry/wxmsg.py#L9)。

**Comment by WMYU** [comment]
请问如何将微信图片保存至本地 目前好像需要手动点一下 微信才会下载到获取到msg.extra 否则的话微信自身不会自动下载到本地，所以解密时也只能解密缩略图msg.thumb
