### ISSUE TITLE
发送中文文件的时候发送失败

### ISSUE THREAD

**Issue by x19990416** [lich0821/WeChatFerry#140]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 发送本地文件的时候失败

**使用环境（请补全下列信息）:**
- win 10  64

- Python 版本：【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
![1711703574086](https://github.com/lich0821/WeChatFerry/assets/9440757/5a3b5dfc-ccc7-408e-bb9a-1dabaab1e0fc)

我尝试了多次，发现文件名为中文的时候失败，英文ok的。请问该如何修改呢

**Comment by lich0821** [comment]
把日志提供一下，估计是编码的问题。

**Comment by x19990416** [comment]
是我程序编码问题，强制转换成utf8就好了

**Comment by x19990416** [comment]
好像还是有问题，我换了一台电脑之后发送中文文件不行，
图一是我程序输入的内容，图二是对应wcf.txt的日志截图。
我程序通过os.path确认文件是存在的，但是在wcf中确说文件不存在。


![1716352945068](https://github.com/lich0821/WeChatFerry/assets/9440757/2d022205-bfee-4cb2-9d63-5bd20032cd20)
![1716353156652](https://github.com/lich0821/WeChatFerry/assets/9440757/d1d217f7-9244-42a3-8230-217ff1ae595a)

**Comment by x19990416** [comment]
em。。。目前测试下来应该是传入的是utf8编码的绝对路径，但是wcf读取文件的时候使用的是gbk编码，我在win11里面设置unicode编码后发送成功了具体设置如图1。
![1716353830658](https://github.com/lich0821/WeChatFerry/assets/9440757/c7069bf7-428f-4799-97a0-652cceaa9a43)
![1716353860497](https://github.com/lich0821/WeChatFerry/assets/9440757/a449f267-627b-4d02-96b3-39d738be69f4)

**Comment by jamesdanner** [comment]
使用rust http 客户端时也出现了这个问题，详细请看 [rust issue](https://github.com/lich0821/wcf-client-rust/issues/15)
