### ISSUE TITLE
@所有人好像有问题

### ISSUE THREAD

**Issue by x19990416** [lich0821/WeChatFerry#144]
我按照文档提示的使用设置aters notify@all 随后没有推送任何消息
wechatferry python 客户端

数据请求：
{
    "msg": "@所有人 这个需要你自己填且后面跟你好之前有个空格 你好呀 这个 at 到底怎么用的",
    "receiver": "xxxx11111@chatroom",
    "aters": "notify@all"
}

**Comment by lich0821** [comment]
请按报BUG模板重新打开报BUG。
