### ISSUE TITLE
[💡SUG] 大佬如何监听一个群进人了

### ISSUE THREAD

**Issue by mggzhu** [lich0821/WeChatFerry#145]

**Comment by lich0821** [comment]
如果只是想知道人进来了，监听消息就可以了。新成员进群会收到一个类型为 `10000` 的消息，内容一般是：

> xxx 通过扫描 yyy 分享的二维码加入群聊

或者

> yyy 邀请 xxx 加入了群聊

如果需要对应wxid，则需要考虑通过昵称反查。但瞬间大量进群，该方法可能实现不了目的。具体还是要看应用场景。

**Comment by mggzhu** [comment]
> 如果只是想知道人进来了，监听消息就可以了。新成员进群会收到一个类型为 `10000` 的消息，内容一般是：
> 
> > xxx 通过扫描 yyy 分享的二维码加入群聊
> 
> 或者
> 
> > yyy 邀请 xxx 加入了群聊
> 
> 如果需要对应wxid，则需要考虑通过昵称反查。但瞬间大量进群，该方法可能实现不了目的。具体还是要看应用场景。

**Comment by mggzhu** [comment]
谢谢大佬
