### ISSUE TITLE
[💡SUG] 能不能适配微信最新版（pc端3.9.10）

### ISSUE THREAD

**Issue by saz97** [lich0821/WeChatFerry#149]
微信系统强制更新，最新版就没法用了呢

**Comment by lich0821** [comment]
See [148](https://github.com/lich0821/WeChatFerry/issues/148)

**Comment by x7yue** [comment]
> See [148](https://github.com/lich0821/WeChatFerry/issues/148)

按给出的方法并不适用全部的账号，有的还是要强制更新。求大佬适配一下最新版orz
