### ISSUE TITLE
获取到群成员列表后，能否判断是否为群主

### ISSUE THREAD

**Issue by yussuy** [lich0821/WeChatFerry#152]
**你希望添加的功能是否与某个问题相关？**
不知道能不能通过获取群列表后判断或者找出哪一个是群主

**描述你希望的解决方案**
目前看列表的第一个好像不一定是群主

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by poo0ooq** [comment]
如果你已经获取到了群成员列表，那么就不存在这个问题了
数组 [0] 就是了

**Comment by yussuy** [comment]
> 如果你已经获取到了群成员列表，那么就不存在这个问题了 数组 [0] 就是了

是这样的，但是其实还是有种特例，比如我是群主，然后设置了一个其他的群管理，我验证后发现群管理有时候是群成员列表[0]，不知道这是通过什么逻辑造成的。

**Comment by iONLY100** [comment]
在数据库[`MicroMsg.db`]中有个表[`ChatRoom`]，[`ChatRoom`]表里的[`Reserved2`]就是
