### ISSUE TITLE
go客户端有点问题，运行不了

### ISSUE THREAD

**Issue by nibabashilkk** [lich0821/WeChatFerry#154]
按照go客户端里面的示例启动的话运行失败，显示拒绝连接。
一开始以为是10086端口被占用，后来换了多个端口还一直是拒绝连接，不知道作者有啥好办法没

**Comment by lich0821** [comment]
请按格式报BUG。随时重新打开。

**Comment by hhdowload** [comment]
请问这个问题解决了吗
