### ISSUE TITLE
增加 Docker 容器化部署

### ISSUE THREAD

**Issue by xjxloveqsl** [lich0821/WeChatFerry#155]
**你希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述你希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by zhlii** [comment]
可以用这个镜像：https://github.com/zhlii/wechat-box

**Comment by xjxloveqsl** [comment]
@zhlii  您好，我pull这个镜像没有权限
报如下的错误：
Step 1/4 : FROM registry.cn-hangzhou.aliyuncs.com/xduo/wine-box:1.0.2
ERROR: Service 'wx-box' failed to build: pull access denied for registry.cn-hangzhou.aliyuncs.com/xduo/wine-box, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by xjxloveqsl** [comment]
@zhlii 哥们，麻烦您能帮我看看如何pull下来么

**Comment by zhlii** [comment]
> @zhlii 哥们，麻烦您能帮我看看如何pull下来么

可以自行构建下：
https://github.com/zhlii/wine-box
https://github.com/zhlii/wine

**Comment by lich0821** [comment]
可以看看这个：https://github.com/Saroth/docker_wechat

**Comment by xjxloveqsl** [comment]
@zhlii @lich0821 多谢

**Comment by xjxloveqsl** [comment]
@zhlii 您好！麻烦问一下，我都构建完成了，然后登录微信时提示版本低，您知道这个是怎么回事么安装时3.9.2版本
