### ISSUE TITLE
Docker 容器化提示微信版本低登录不上

### ISSUE THREAD

**Issue by xjxloveqsl** [lich0821/WeChatFerry#161]
**你希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述你希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by lich0821** [comment]
这个不是容器的问题，是低版本的问题，目前没有办法，等后续升级吧

**Comment by chimojiacai** [comment]
求 Dockerfile 🙏

**Comment by danni-cool** [comment]
我已经封装了新docker镜像，可以支持远程rpc调用 https://github.com/danni-cool/wechatbot-provider-windows，完美适配各个wechatferry 客户端

**Comment by xiaowu-ai-crypto** [comment]
> 美适配 wechatferry 客户端

![WechatIMG59](https://github.com/user-attachments/assets/410a1bb0-eb26-4626-b780-784ce8c0d86e)
当这个StartService 启动后，每次微信就自动退出啦，怎么都无法运行

**Comment by danni-cool** [comment]
硬件配置达标了么

**Comment by xiaowu-ai-crypto** [comment]
https://github.com/user-attachments/assets/7cfabd9e-51d1-4f7e-8a63-14ae326d7839

硬件配置肯定是达标的。每次StartService启动都会出现图片红框的小弹框，应该是一个报错。输出里面没显示错误所以不知道是错误是什么。但是不点这个弹框的话，程序一直在initialize_sdk（）里面。点了弹框的话，微信就直接退出了。
![WX20240806-132542@2x](https://github.com/user-attachments/assets/c8d83fdb-ded0-4ee3-b9dc-d88530ec52d9)
![WX20240806-132956](https://github.com/user-attachments/assets/1c158d5a-d7eb-46e2-a044-ca87b1f2331b)

**Comment by danni-cool** [comment]
扫码登陆完再启动service呢？wine环境的报错确实很迷，也不好给出修复方案。

**Comment by xiaowu-ai-crypto** [comment]
> 扫码登陆完再启动service呢？wine环境的报错确实很迷，也不好给出修复方案。

不管是扫码登陆完再启动service还是先service在启动，都是一样的错误。我也不了解wine环境，不知道从哪里下手去解决问题

**Comment by danni-cool** [comment]
据我所知，除非你是用的模拟的x86环境，比如mac上跑模拟x86 docker 镜像会出现类似问题，纯正x86硬件环境应该是好的

**Comment by xiaowu-ai-crypto** [comment]
> 据我所知，除非你是用的模拟的x86环境，比如mac上跑模拟x86 docker 镜像会出现类似问题，纯正x86硬件环境上跑应该是好的

我这不是模拟环境，就是x86物理环境。😑😑
![WX20240807-171710](https://github.com/user-attachments/assets/b58a392b-eb7b-49a7-9d7b-b6696c5c35d7)

**Comment by Saroth** [comment]
> 我已经封装了新docker镜像，可以支持远程rpc调用 https://github.com/danni-cool/wechatbot-provider-windows
> 
> 完美适配 wechatferry 客户端

就觉得您这工程很眼熟，原来是我的fork版，哈哈 [捂脸]。
这次WeChatFerry改成使用客户端注入后，给容器化部署上了点难度。
我正在寻找合适的解决方案，顺便来抄下作业 :)

**Comment by Saroth** [comment]
> > 我已经封装了新docker镜像，可以支持远程rpc调用 https://github.com/danni-cool/wechatbot-provider-windows
> > 完美适配 wechatferry 客户端
> 
> 就觉得您这工程很眼熟，原来是我的fork版，哈哈 [捂脸]。 这次WeChatFerry改成使用客户端注入后，给容器化部署上了点难度。 我正在寻找合适的解决方案，顺便来抄下作业 :)

终于搞定了，https://github.com/Saroth/docker_wechat。
* 已支持WeChatFerry的v39.2.4版本。用Go写了个简易注入器，避免了在容器里安装其他依赖。
* 改进了配置，把应用和注册表数据放在宿主机，避免了容器在重置后需要再重装微信。现在容器可以随意删掉再重启镜像了。
