### ISSUE TITLE
运行run.py文件报错

### ISSUE THREAD

**Issue by adb1145141** [lich0821/WeChatFerry#164]
求助！运行run.py文件报错
2024-06-26 23:02:48 wcferry version: 39.0.14.1
2024-06-26 23:02:56 初始化失败！
2024-06-26 23:02:56,866 WCF ERROR client.py::init[80]:初始化失败
微信版本3.9.11
python版本3.12.4
<img width="407" alt="截屏2024-06-26 23 06 01" src="https://github.com/lich0821/WeChatFerry/assets/170862896/ffd8ec91-af96-4f07-ada4-b32e0134b4ab">
<img width="407" alt="截屏2024-06-26 23 06 07" src="https://github.com/lich0821/WeChatFerry/assets/170862896/fb8614fd-0c13-471e-8946-aae62385e59d">

**Comment by lich0821** [comment]
[【FAQ】WeChatFerry 机器人常见问题 v39.0.14](https://mp.weixin.qq.com/s/eMQgP1TiEqAxmpxYljSgeg)
