### ISSUE TITLE
发送群消息@失效 

### ISSUE THREAD

**Issue by xjxloveqsl** [lich0821/WeChatFerry#166]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
- 是否安装后第一次启动就出现？一直存在
- 重启微信后能否解决？否

**使用环境（请补全下列信息）:**
- 操作系统：linux上的docker系统使用的是wine
- 操作系统版本：64位

请求的参数的样例数据
{
  "aters": ["鑫wxid"],
   "msg": "@鑫 你好",
  "receiver": "群id"
}

**Comment by lich0821** [comment]
这个“BUG”报几百回了。
先看 [FAQ](https://mp.weixin.qq.com/s/eMQgP1TiEqAxmpxYljSgeg)，还解决不了的按格式报 BUG。

**Comment by xjxloveqsl** [comment]
您好，我按照文档的方式测试了，用的gohttp客户端，但是@依然不生效，wxid没有改过格式也正确

**Comment by lich0821** [comment]
> 您好，我按照文档的方式测试了，用的gohttp客户端，但是@依然不生效，wxid没有改过格式也正确

可以去客户端那边提个 issue 看看。

**Comment by xjxloveqsl** [comment]
好的，多谢

**Comment by chimojiacai** [comment]
@xjxloveqsl 你好，Dockerfile 能分享一份吗？🙏

**Comment by xjxloveqsl** [comment]
@chimojiacai  https://github.com/lich0821/WeChatFerry/issues/155参考这个就能制作

**Comment by xjxloveqsl** [comment]
@chimojiacai https://github.com/lich0821/WeChatFerry/issues/155 请参考这个
