### ISSUE TITLE
is_at匹配不到被@的人

### ISSUE THREAD

**Issue by Can-Li** [lich0821/WeChatFerry#170]
不清楚是我自己设备的问题还是什么原因，反正@了就是匹配不到

    def is_at(self, wxid) -> bool:
        """是否被 @：群消息，在 @ 名单里，并且不是 @ 所有人"""
        if not self.from_group():
            return False  # 只有群消息才能 @

        if not re.findall(f"<atuserlist>.*({wxid}).*</atuserlist>", self.xml):
            return False  # 不在 @ 清单里

        if re.findall(r"@(?:所有人|all|All)", self.content):
            return False  # 排除 @ 所有人

        return True

我把f"<atuserlist>.*({wxid}).*</atuserlist>"替换成r"<atuserlist>\s*<!\[CDATA\[([^\]]*)\]\]>\s*</atuserlist>"，就能正常匹配到了

如果是BUG,希望作者可以改一下

**Comment by lich0821** [comment]
请提供消息报文，注意敏感信息脱敏。

**Comment by Can-Li** [comment]
> 请提供消息报文，注意敏感信息脱敏。
这是我的xml输出的内容，但是你的正则似乎匹配不到
上一条消息正则被转义了
这是你的源码
```regex  
f"<atuserlist>.*({wxid}).*</atuserlist>"
```
这是我改了过后的
```regex  
r"<atuserlist>\s*<!\[CDATA\[([^\]]*)\]\]>\s*</atuserlist>"  
```
<msgsource>
    <atuserlist>
        <![CDATA[wxid_64t7us4c******,wxid_gs839e7g******]]>
    </atuserlist>
    <pua>1</pua>
    <silence>0</silence>
    <membercount>5</membercount>
    <signature>V1_0VC1JGkS|v1_0VC1JGkS</signature>
    <tmp_node>
        <publisher-id />
    </tmp_node>
    <sec_msg_node>
        <alnode>
            <fr>1</fr>
        </alnode>
    </sec_msg_node>
</msgsource>

**Comment by Can-Li** [comment]
> > 请提供消息报文，注意敏感信息脱敏。
> > 这是我的xml输出的内容，但是你的正则似乎匹配不到
> > 上一条消息正则被转义了
> > 这是你的源码
> 
> ```regexp
> f"<atuserlist>.*({wxid}).*</atuserlist>"
> ```
> 
> 这是我改了过后的
> 
> ```regexp
> r"<atuserlist>\s*<!\[CDATA\[([^\]]*)\]\]>\s*</atuserlist>"  
> ```
> 
> 1 0 5 V1_0VC1JGkS|v1_0VC1JGkS 1
XML也被转义了，我重发一次，这是XML
```regex 
<msgsource>
    <atuserlist>
        <![CDATA[wxid_64t7us4cpkon22,wxid_gs839e7g4v0622]]>
    </atuserlist>
    <pua>1</pua>
    <silence>0</silence>
    <membercount>5</membercount>
    <signature>V1_0VC1JGkS|v1_0VC1JGkS</signature>
    <tmp_node>
        <publisher-id />
    </tmp_node>
    <sec_msg_node>
        <alnode>
            <fr>1</fr>
        </alnode>
    </sec_msg_node>
</msgsource>
```

**Comment by lich0821** [comment]
> ```regexp
> <msgsource>
>     <atuserlist>
>         <![CDATA[wxid_64t7us4c8******,wxid_gs839e7*******]]>
>     </atuserlist>
>     <pua>1</pua>
>     <silence>0</silence>
>     <membercount>5</membercount>
>     <signature>V1_0VC1JGkS|v1_0VC1JGkS</signature>
>     <tmp_node>
>         <publisher-id />
>     </tmp_node>
>     <sec_msg_node>
>         <alnode>
>             <fr>1</fr>
>         </alnode>
>     </sec_msg_node>
> </msgsource>
> ```

所有被@的报文都长这样吗？还是什么情况下才会这样？

**Comment by Can-Li** [comment]
> > ```regexp
> > <msgsource>
> >     <atuserlist>
> >         <![CDATA[wxid_64t7us4c8******,wxid_gs839e7*******]]>
> >     </atuserlist>
> >     <pua>1</pua>
> >     <silence>0</silence>
> >     <membercount>5</membercount>
> >     <signature>V1_0VC1JGkS|v1_0VC1JGkS</signature>
> >     <tmp_node>
> >         <publisher-id />
> >     </tmp_node>
> >     <sec_msg_node>
> >         <alnode>
> >             <fr>1</fr>
> >         </alnode>
> >     </sec_msg_node>
> > </msgsource>
> > ```
> 
> 所有被@的报文都长这样吗？还是什么情况下才会这样？

这是我的源码，我打印了你代码中的self.xml，输出的xml就是上面的内容

`from wcferry import Wcf

wcf = Wcf()

wcf.enable_receiving_msg(pyq=True)
print(wcf.is_receiving_msg())



while True:
    try:
        msg = wcf.get_msg()
        print(msg.is_at('wxid_64t7us4cpkon22'))
        print(msg.content)
    except Exception as e:
        print(e)
        continue
`
