### ISSUE TITLE
go_wcf_http客户端

### ISSUE THREAD

**Issue by xjxloveqsl** [lich0821/WeChatFerry#178]
大师，您好！
版本[v39.2.3.0]
1 新的golang客户端接收消息没有extra这个字段了
2 是否能增加下载图片的和文件的功能

多谢

**Comment by lich0821** [comment]
go客户端比较多，具体是哪个？

**Comment by xjxloveqsl** [comment]
@xjxloveqsl 您好，是[go_wcf_http](https://github.com/lich0821/WeChatFerry/tree/master/clients/go_wcf_http) 这个客户端

**Comment by lich0821** [comment]
> @xjxloveqsl 您好，是[go_wcf_http](https://github.com/lich0821/WeChatFerry/tree/master/clients/go_wcf_http) 这个客户端

@yitiaoaishuijiaodexianyu

**Comment by xjxloveqsl** [comment]
@xjxloveqsl go_您好，go_wcf_http和之前gohttp客户端比较，少了很多功能，能否能增加下载图片和文件的功能

**Comment by yitiaoaishuijiaodexianyu** [comment]
@xjxloveqsl 目前还没看到dll实现，需要等dll实现之后可以加入， extra字段应该是在xml中

**Comment by xjxloveqsl** [comment]
@yitiaoaishuijiaodexianyu 好的，多谢

**Comment by lich0821** [comment]
> @xjxloveqsl 目前还没看到dll实现，需要等dll实现之后可以加入， extra字段应该是在xml中

这是客户端自己实现的，赶紧干活

**Comment by yitiaoaishuijiaodexianyu** [comment]
@lich0821 我不 我要摆烂

**Comment by xjxloveqsl** [comment]
@yitiaoaishuijiaodexianyu 
您好，我自己实现的获取指定群成员成功，能获取出来，但是不知道是否有更好的办法
![image](https://github.com/lich0821/WeChatFerry/assets/36986360/16b4cf83-39c3-4e2f-958c-6868998eaf83)

**Comment by yitiaoaishuijiaodexianyu** [comment]
@xjxloveqsl 目前我还没研究。

**Comment by WyntersN** [comment]
@xjxloveqsl 下载图片啥时候更新，DownloadAttach已经无法下载图片了

**Comment by WyntersN** [comment]
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/b0b5ba29-587a-47ff-835b-9cd5dabc3987)

Functions_name 和 Functions_value 在哪里可以看到

**Comment by xjxloveqsl** [comment]
@WyntersN 获取消息中的thumb,extra和message_id先调用DownloadAttach这个方法下载图片dat文件，然后解密dat文件成图片，我测试是可以下载下来的

**Comment by WyntersN** [comment]
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/7813cf10-bf53-4c4a-9838-927173bca505)

go客户端源代码 thumb 是空的 能下载吗

**Comment by xjxloveqsl** [comment]
@WyntersN 按理说应该也是可以的，你可以试试，我是都设置了

**Comment by WyntersN** [comment]
@xjxloveqsl 
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/c81cbacc-5d36-419e-8304-50eb5ce7da62)
我这里提示 超时

**Comment by xjxloveqsl** [comment]
@WyntersN 我用的是http的，回调你的服务正常么

**Comment by WyntersN** [comment]
@xjxloveqsl 
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/de807ea4-b576-4b7b-8396-60a5d7b9a68e)

**Comment by xjxloveqsl** [comment]
@WyntersN 返回0应该就是成功了吧，是不是会在extra的目录下找到dat文件

**Comment by WyntersN** [comment]
就是没有这个 .dat 文件

**Comment by WyntersN** [comment]
> ![image](https://private-user-images.githubusercontent.com/36986360/347390568-717d9b39-1514-4096-9b0f-005a0a31e6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTMyMDgsIm5iZiI6MTcyMDYxMjkwOCwicGF0aCI6Ii8zNjk4NjM2MC8zNDczOTA1NjgtNzE3ZDliMzktMTUxNC00MDk2LTliMGYtMDA1YTBhMzFlNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZmExNzFiYjVkZmFiYTZlNWRjYzE3NWI0ZDkyNDhmZTk5ODNmMjcwODcwMjYwZGI0ODkwZGU4NDIzNTJiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b3tuVnez8nWBl4JdWgiUd4vt0nxgBFcbhTCl8bkgVjU) 你这个目录下没有找到么

没有找到，要我自己图片点一下才出来

**Comment by WyntersN** [comment]
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/1fb90f0f-7618-4978-86f6-f9d428b51b37)

**Comment by xjxloveqsl** [comment]
@WyntersN 首先你得先获取回调的消息，然后拿消息里的message_id,thumb,extra 然后调用
![image](https://github.com/lich0821/WeChatFerry/assets/36986360/c0c3eb19-2252-4953-b9f7-eaab25a1d394)
这个方法传
![image](https://github.com/lich0821/WeChatFerry/assets/36986360/afdd6405-4c5e-47db-ac44-9f8d610636f1)
这三个参数

**Comment by xjxloveqsl** [comment]
@WyntersN 调用/api/SetMessageCallbackUrl这个接口注册回调地址，接收消息

**Comment by WyntersN** [comment]
我知道，我是直接传参数调用函数的下载不下载

**Comment by xjxloveqsl** [comment]
@WyntersN 我就是按照调用这个接口下载下来了

**Comment by WyntersN** [comment]
@xjxloveqsl 
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/245fff01-4164-43f4-96d1-83f6b67bc57b)
回调中怎么没 Extra

**Comment by WyntersN** [comment]
> @WyntersN 我就是按照调用这个接口下载下来了

下载附件传值 是不是传 msg_id 和 .dat的路径

**Comment by xjxloveqsl** [comment]
@WyntersN 
![image](https://github.com/lich0821/WeChatFerry/assets/36986360/0c18a93f-a7f6-44a3-8ace-e5363006d0d9)
加上这两个字段，在信息就有了 传dat 全路径

**Comment by lich0821** [comment]
> @xjxloveqsl ![image](https://private-user-images.githubusercontent.com/27792650/347394815-245fff01-4164-43f4-96d1-83f6b67bc57b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjMzNjgsIm5iZiI6MTcyMDYyMzA2OCwicGF0aCI6Ii8yNzc5MjY1MC8zNDczOTQ4MTUtMjQ1ZmZmMDEtNDE2NC00M2Y0LTk2ZDEtODNmNmI2N2JjNTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjE2NTYwY2RiODRmYWVkODc3ODYxYzk1OGI3MjE3NGM0MDk0YzEzZTM2YTE3NzY5ODIzODA4NzFhY2RmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mD73NVL4kelq9_ZvRfQjetD6fwrSLol1YBAvbG0auvQ) 回调中怎么没 Extra

@yitiaoaishuijiaodexianyu 你是不是干活只干了一半。。。

**Comment by WyntersN** [comment]
> @WyntersN ![image](https://private-user-images.githubusercontent.com/36986360/347418695-0c18a93f-a7f6-44a3-8ace-e5363006d0d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjgxNjYsIm5iZiI6MTcyMDYyNzg2NiwicGF0aCI6Ii8zNjk4NjM2MC8zNDc0MTg2OTUtMGMxOGE5M2YtYTdmNi00NGEzLThhY2UtZTUzNjMwMDZkMGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzQ0ZTdjOWY2YzQwM2Y0ZjlmMDA0N2JjZDRhYWQ2NmEzNTlmNzdhNGI0M2ZmZDliMmFhOGE3MjkwMDc5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZFkRMf-l4vgPlN4BCXWB9AnQK4biK80CMPSDJ8017oA) 加上这两个字段，在信息就有了 传dat 全路径


@xjxloveqsl 
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/9f80aa2a-056a-4471-a2ad-23b0276a6ff2)


为什么我的会这样

**Comment by xjxloveqsl** [comment]
@WyntersN 粘贴curl命令去主机上调用

**Comment by yitiaoaishuijiaodexianyu** [comment]
我用不到这个功能啊 我就没测- .-

**Comment by WyntersN** [comment]
> @WyntersN 粘贴curl命令去主机上调用

我就是在本地调用的
