### ISSUE TITLE
只支持获取朋友圈，不支持发朋友圈么？

### ISSUE THREAD

**Issue by ysn2382617094wsw** [lich0821/WeChatFerry#179]
只支持获取朋友圈，不支持发朋友圈么？

**Comment by v200123** [comment]
微信客户端也没实现发送朋友圈呀

**Comment by joe12801** [comment]
> 微信客户端也没实现发送朋友圈呀

有的，只不过是隐藏了，以前低版本有发朋友圈，不过要下载低版本来分析，上面的那些HOOK有发朋友圈的

**Comment by holalc776** [comment]
> 只支持获取朋友圈，不支持发朋友圈么？

怎么获取朋友圈的呀！
