### ISSUE TITLE
[💡SUG] 希望增加ws client支持

### ISSUE THREAD

**Issue by jwjjgs** [lich0821/WeChatFerry#18]
**你希望添加的功能是否与某个问题相关？**
目前我看到的是启动的server，希望可以支持启动websocket client

**描述你希望的解决方案**
传入ip和port 自动连接 websocket 断线重连

**描述你考虑的替代方案**

**其他**

**Comment by lich0821** [comment]
ws是挺好的，不过已经使用了RPC，再搞ws没啥动力。你有兴趣实现吗？

**Comment by bosslizhiyong** [comment]
希望实现http

**Comment by jwjjgs** [comment]
> ws是挺好的，不过已经使用了RPC，再搞ws没啥动力。你有兴趣实现吗？

大佬，要是能作为client就好了，我是nodejs，对c++不熟悉，惭愧😭😭😭

**Comment by lich0821** [comment]
> > ws是挺好的，不过已经使用了RPC，再搞ws没啥动力。你有兴趣实现吗？
> 
> 大佬，要是能作为client就好了，我是nodejs，对c++不熟悉，惭愧😭😭😭

如果只是使用，其实可以用 NodeJS 封装一个 client 就可以了，不过需要处理一下 TCP 和 Protocol Buffers。你要有兴趣咱们可以一起搞一下喔 @jwjjgs

**Comment by yaoyaochil** [comment]
> > ws是挺好的，不过已经使用了RPC，再搞ws没啥动力。你有兴趣实现吗？
> 
> 大佬，要是能作为client就好了，我是nodejs，对c++不熟悉，惭愧😭😭😭

+1111111  nodejs连接这个rpc 有点难受 我搞了两天啦 你搞定了吗 各种方法都试了

**Comment by stkevintan** [comment]
@yaoyaochil nodejs wcf 和websocket客户端我已经实现了 https://github.com/stkevintan/node-wcferry
 欢迎contribute
