### ISSUE TITLE
[🐛BUG] go客户端消息监听不了

### ISSUE THREAD

**Issue by WyntersN** [lich0821/WeChatFerry#181]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
- 是否安装后第一次启动就出现？
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？

**使用环境（请补全下列信息）:**
- 操作系统：win11
- 操作系统版本：64
- Go 版本： 1.22.0

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![image](https://github.com/lich0821/WeChatFerry/assets/27792650/e96545a0-7620-4f1c-a9a9-f010722e7c73)

![image](https://github.com/lich0821/WeChatFerry/assets/27792650/e4228e98-0f9f-4c94-a5c4-f2abe4cd7916)

![image](https://github.com/lich0821/WeChatFerry/assets/27792650/fdd525f3-c427-4434-8b47-b6672461f8ad)

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
这是`bug`？ @yitiaoaishuijiaodexianyu
