### ISSUE TITLE
go_wcf_http下载附件的问题

### ISSUE THREAD

**Issue by xjxloveqsl** [lich0821/WeChatFerry#183]
**描述这个 bug**
版本[v39.2.3.0]  go_wcf_http客户端，在调用下载附件的接口，偶尔会出现崩溃的问题，导致go的客户段接口被调用就超时
只有重启客户端重新注入才能好使，没找到原因

**Comment by lich0821** [comment]
要不你来维护吧。那货提交完就不管了……

**Comment by xjxloveqsl** [comment]
@lich0821 好的，有时间我更新一下

**Comment by lich0821** [comment]
下载`图片`、`视频`、`文件`都是这个方法。这个方法是异步的，只需要触发一次即可，然后需要轮询完成状态（可能有事件，但没去找）。
传参数可以参考：
* [int DownloadAttach(QWORD id, string thumb, string extra)](https://github.com/lich0821/WeChatFerry/blob/master/WeChatFerry/spy/funcs.cpp#L232)
* [def download_image(self, id: int, extra: str, dir: str, timeout: int = 30) -> str](https://github.com/lich0821/WeChatFerry/blob/master/clients/python/wcferry/client.py#L821)

**Comment by xjxloveqsl** [comment]
@lich0821 好的
