### ISSUE TITLE
wcferry 39.2.4.0。在运行wechatrobot时，未能自动通过好友申请

### ISSUE THREAD

**Issue by dlq99** [lich0821/WeChatFerry#185]
**描述这个 bug**
wcferry 39.2.4.0。在运行wechatrobot时，未能自动通过好友申请
        if msg.type == 37:  # 好友请求
            self.autoAcceptFriendRequest(msg)
仍然在新的朋友列表中等待通过。

**使用环境（请补全下列信息）:**
- 操作系统：【Windows 10】
- 操作系统版本：【4 位】
- Python 版本：【3.10】

**Comment by lich0821** [comment]
- 查询登录状态
- 获取登录账号信息
- 获取消息类型
- 获取联系人
- 获取可查询数据库
- 获取数据库所有表
- 获取语音消息
- 发送文本消息（可 @）
- 发送图片消息
- 发送文件消息
- 发送卡片消息
- 发送 GIF 消息
- 拍一拍群友
- 转发消息
- 开启接收消息
- 关闭接收消息
- 查询数据库
- 获取朋友圈消息
- 下载图片、视频、文件
- 解密图片
- 添加群成员
- 删除群成员
- 邀请群成员

**Comment by github-ShiQi** [comment]
对，我今天也遇到了
