### ISSUE TITLE
[🐛BUG] 非安装微信时所用用户下，注册表读不到微信路径

### ISSUE THREAD

**Issue by Menci** [lich0821/WeChatFerry#186]
**描述这个 bug**

![1de737aac7851018a9212a1e99de6ded](https://github.com/user-attachments/assets/a26543c2-7057-4a0e-90e1-837d9bad7a1d)

`GetWeChatPath()` 读不到注册表 HKCU 下的安装路径 key，最终导致获取不到微信版本，拒绝启动。

![429f6cf6493569fe24080aa849fa1c10](https://github.com/user-attachments/assets/79cd8059-1c91-44d2-ae34-a0d7233a77d2)

**使用环境（请补全下列信息）:**
- 操作系统：Windows Server 2021
- 操作系统版本：x64

**屏幕截图**

![3d65437d4a2aaa239785143bf7638fc6](https://github.com/user-attachments/assets/60e5155f-e6cc-4281-ba60-eefa25243830)

代码里读了 HKCU，怀疑是因为我这个账户不是管理员账户，而要读的这个 key 在管理员账户下面。

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
感谢反馈～不过这可能是 Windows 权限管理的 `FEATURE`。
