### ISSUE TITLE
自定义消息监听端口 10087

### ISSUE THREAD

**Issue by supermoonie** [lich0821/WeChatFerry#190]
**你希望添加的功能是否与某个问题相关？**
否

**描述你希望的解决方案**
wx_init_sdk 方法增加消息监听端口参数，10087 和贝锐蒲公英监听的端口冲突

**描述你考虑的替代方案**
无

**其他**
![image](https://github.com/user-attachments/assets/6d95b880-85bb-45a8-82f7-6d7f21934a88)

**Comment by lich0821** [comment]
[int WxInitSDK(bool debug, int port)](https://github.com/lich0821/WeChatFerry/blob/bf8e6bddb90cbb9aa6a34efcc47d2a2b9e85f8d7/WeChatFerry/sdk/sdk.cpp#L34)
