### ISSUE TITLE
[🐛BUG] wcferryV39.0.12.0，有用户撤回消息时，是可以收到通知的，39.2.4.0版本没有通知

### ISSUE THREAD

**Issue by Li1Fan** [lich0821/WeChatFerry#192]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
使用python调用wcferry库的get_msg，实时监听消息
wcferryV39.0.12.0，有用户撤回消息时，是可以收到通知的，39.2.4.0版本却没有通知，问题必现

**使用环境（请补全下列信息）:**
- 操作系统：【Windows 10】
- 操作系统版本：【64 位】
- Python 版本：【3.8.15 64 位等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
Closing this as a duplicate of #162. Please follow up there.

**Comment by isqyz** [comment]
> [将此作为#162](https://github.com/lich0821/WeChatFerry/issues/162)的重复关闭。请跟进。

这几个帖调来调去的，晕了
