### ISSUE TITLE
[🐛BUG] wcferryV39.0.12.0，撤回消息可以正常调用，39.2.4.0版本调用后没有成功撤回

### ISSUE THREAD

**Issue by Li1Fan** [lich0821/WeChatFerry#193]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- wcferryV39.0.12.0，撤回消息revoke_msg()函数，可以正常调用，39.2.4.0版本调用后没有却成功撤回，日志中没有报错信息
- 撤回消息传入的id是通过消息发出去一段时间后，数据库MSG0.db中的MSG表，会刷新MsgSvrID值，再进行revoke_msg的调用

**使用环境（请补全下列信息）:**
- 操作系统：【如 Windows 10,等】
- 操作系统版本：【64 位】
- Python 版本：【3.8.15 64 位 】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
Closing this as a duplicate of #192
