### ISSUE TITLE
[💡SUG] 可不可以直接在命令行下注入，然后用API工具调用HTTP接口的教程或者方法？

### ISSUE THREAD

**Issue by hiyaabai** [lich0821/WeChatFerry#195]
教程和方法能否细致一些，方便小白入门。
命令行方式怎么注入和启动，常见代码怎么注入和启动，如何判断成功和失败，如何用工具调试接口进行简单验证，简单的示例即可，谢谢。

**Comment by lich0821** [comment]
如果熟悉 `Python` 的话，可以参考 [这个](https://github.com/lich0821/WeChatFerry/blob/3.9.2.23/clients/python/wcferry/client.py#L78)

**Comment by hiyaabai** [comment]
感谢您的回复，请问可以提供编译好的DLL和注入程序吗，我记得之前的版本好像有提供，VC编译环境设置总是不通过。

**Comment by lich0821** [comment]
1. 以前有，直接翻旧版就可以了（注意 DLL 版本）
2. 可以使用 github action 编译，项目自带的
