### ISSUE TITLE
感謝，能用

### ISSUE THREAD

**Issue by MarkGor** [lich0821/WeChatFerry#2]
項目能使用，
由於我個人不熟悉PY，所以根據幾個不同的demo拼湊起來使用，PY把消息轉發到服務端然後再根據結果執行回復。
不過希望能增加下PY封裝的SDK說明文檔。

**Comment by MarkGor** [comment]
另外可行的話希望增加企業微信的支持

**Comment by lich0821** [comment]
> 項目能使用， 由於我個人不熟悉PY，所以根據幾個不同的demo拼湊起來使用，PY把消息轉發到服務端然後再根據結果執行回復。 不過希望能增加下PY封裝的SDK說明文檔。

Hello，可以參考這個框架：[WeChatRobot](https://github.com/lich0821/WeChatRobot)。

**Comment by lich0821** [comment]
> 另外可行的話希望增加企業微信的支持

我記得企業微信有現成的接口，可以直接使用的。如果說是收發企業微信用戶消息，由於我沒有企業微信，無法調試，你若有環境，歡迎PR
