### ISSUE TITLE
http接口文档在哪 [💡SUG] 一句话描述你希望新增的功能或特性

### ISSUE THREAD

**Issue by bosslizhiyong** [lich0821/WeChatFerry#20]
**你希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述你希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by bosslizhiyong** [comment]
http接口文档在哪

**Comment by lich0821** [comment]
[这里](https://github.com/lich0821/WeChatRobot/blob/master/main.py#L43)
```
暴露 HTTP 接口供发送消息，需要在配置文件中取消 http 注释
接口文档：http://localhost:9999/docs
访问示例：
1. 浏览器访问：http://localhost:9999/send?msg=hello%20world&receiver=filehelper
2. curl -X 'GET' 'http://localhost:9999/send?msg=hello%20world&receiver=filehelper' -H 'accept: application/json'
```

**Comment by lich0821** [comment]
> http接口文档在哪

[https://wechatferry.readthedocs.io/](https://wechatferry.readthedocs.io/)
