### ISSUE TITLE
自动添加好友，该方法在新版本中失效

### ISSUE THREAD

**Issue by wangtu** [lich0821/WeChatFerry#200]
**描述这个 bug**
wcf的自动添加好友方法accept_new_friend无效，该方法在python引入新版本（微信3.9.10.27）失效

- 什么问题？
答：accept_new_friend 自动通过好友申请不支持，回滚到旧版本sdk（3.9.2.23）则支持无问题

**使用环境（请补全下列信息）:**
- 操作系统：【 Windows 10】
- 操作系统版本：【 64 位】
- Python 版本：【如 3.9.6  64位，3.11 64位 两种】

**现象**
无任何反应

**异常代码**
# 自动添加好友，该方法在新版本中失效
 def autoAcceptFriendRequest(self, msg: WxMsg) -> None:
        try:
            xml = ET.fromstring(msg.content)
            v3 = xml.attrib["encryptusername"]
            v4 = xml.attrib["ticket"]
            scene = int(xml.attrib["scene"])
            self.wcf.accept_new_friend(v3, v4, scene)

        except Exception as e:
            self.LOG.error(f"同意好友出错：{e}")

**Comment by lich0821** [comment]
Closing this as a duplicate of #196

**Comment by DeMoth-1** [comment]
请问为什么新版没有接受好友申请了？应该如何再次实现?
