### ISSUE TITLE
[🐛BUG] v39.2.4 使用 get_info_by_wx_id 返回空数据

### ISSUE THREAD

**Issue by imococo** [lich0821/WeChatFerry#202]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
v39.2.4 使用 get_info_by_wx_id 返回空数据

**使用环境（请补全下列信息）:**
- 操作系统：Windows专业版
- 操作系统版本：64 位
- Python 版本：试过3.10.11，3.12.4 都不行

**Comment by lich0821** [comment]
Closing this as a duplicate of #196
