### ISSUE TITLE
[💡SUG] SDK级支持传入 微信 pid 实现动态注入

### ISSUE THREAD

**Issue by minikey** [lich0821/WeChatFerry#203]
**描述你希望的解决方案**
在构造函数中支持 wxpid 传入，如果有微信进程id直接使用，并完成注入

**描述你考虑的替代方案**
在 SDK 级别有函数完成指定pid注入

**Comment by minikey** [comment]
搜到历史了，看来是不好实现了

**Comment by lich0821** [comment]
> 搜到历史了，看来是不好实现了

这不是技术问题。普通玩家不会有这需求的；有这需求的，多数是要搞事情的。本项目反对搞事情。

**Comment by MemoryCollection** [comment]
双开微信，想让他只注入小号，没有服务器单独上微信
