### ISSUE TITLE
[🐛BUG] 测试了几个版本，get_info_by_wxid 都返回空数据

### ISSUE THREAD

**Issue by imococo** [lich0821/WeChatFerry#204]
**描述这个 bug**
测试了几个版本，get_info_by_wxid 都返回空数据
测试版本有：v39.2.4，

**使用环境（请补全下列信息）:**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：【32 位 或 64 位】
- Python 版本：【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
Closing this as a duplicate of #196
