### ISSUE TITLE
[Go Http客户端] 朋友圈消息无法成功保存到数据库

### ISSUE THREAD

**Issue by alva1211** [lich0821/WeChatFerry#205]
原因是刷新朋友圈之后获取到的朋友圈信息的id超过的数据库message表id（int）的范围

报错信息：

time=2024-08-14T10:16:18.650+08:00 level=ERROR msg="trace error" Logger=gorm error="sql: converting argument $1 type: uint64 values with high bit set are not supported" sql="INSERT INTO message (id,is_self,is_group,type,ts,roomid,content,sender,sign,thumb,extra,xml,remark,created_at,updated_at) VALUES (14458594525450547936,false,false,0,1723598781,\"-\",\"********************\",\"wxid_p19dofnd1zpj22\",\"\",\"\",\"\",\"<TimelineObject><id><![CDATA[14458594525450547936]]></id><username><![CDATA[wxid_p19dofnd1zpj22]]></username><createTime><![CDATA[1723598781]]></createTime><contentDescShowType>0</contentDescShowType><contentDescScene>0</contentDescScene><private><![CDATA[0]]></private><contentDesc><![CDATA[⚠️安全生产许可证，需提前3个月延期\n💢到期不能公开投标，影响施工\n📣需要安许延期的客户抓紧时间\n☎️一站式申报服务 ，免费咨询]]></contentDesc><contentattr><![CDATA[0]]></contentattr><sourceUserName></sourceUserName><sourceNickName></sourceNickName><statisticsData></statisticsData><weappInfo><appUserName></appUserName><pagePath></pagePath><version><![CDATA[0]]></version><isHidden>0</isHidden><debugMode><![CDATA[0]]></debugMode><shareActionId></shareActionId><isGame><![CDATA[0]]></isGame><messageExtraData></messageExtraData><subType><![CDATA[0]]></subType><preloadResources></preloadResources></weappInfo><canvasInfoXml></canvasInfoXml><ContentObject><contentStyle><![CDATA[1]]></contentStyle><contentSubStyle><![CDATA[0]]></contentSubStyle><title></title><description></description><contentUrl></contentUrl><mediaList><media><id><![CDATA[14458594526072025824]]></id><type><![CDATA[2]]></type><title></title><description></description><private><![CDATA[0]]></private><url type=\"\"1\"\" md5=\"\"a7406f99e52c2983141531f644756ced\"\"><![CDATA[http://shmmsns.qpic.cn/mmsns/UDT6e41Bw6LnGw8dvibJ49YwiawWCazzA4YZ8a6LJeQK89V1gksbHjiaiaDeJd5gud9KSib68H4Y6Xo0/0]]></url><thumb type=\"\"1\"\"><![CDATA[http://shmmsns.qpic.cn/mmsns/UDT6e41Bw6LnGw8dvibJ49YwiawWCazzA4YZ8a6LJeQK89V1gksbHjiaiaDeJd5gud9KSib68H4Y6Xo0/150]]></thumb><videoDuration><![CDATA[0.0]]></videoDuration><size totalSize=\"\"51150.0\"\" width=\"\"800.0\"\" height=\"\"800.0\"\"></size></media></mediaList></ContentObject><actionInfo><appMsg><mediaTagName></mediaTagName><messageExt></messageExt><messageAction></messageAction></appMsg></actionInfo><appInfo><id></id></appInfo><location poiClassifyId=\"\"\"\" poiName=\"\"\"\" poiAddress=\"\"\"\" poiClassifyType=\"\"0\"\" city=\"\"\"\"></location><publicUserName></publicUserName><streamvideo><streamvideourl></streamvideourl><streamvideothumburl></streamvideothumburl><streamvideoweburl></streamvideoweburl></streamvideo></TimelineObject>\",\"\",1723601778,1723601778) RETURNING rd" rows=0 elapsed=9.5544ms

**Comment by lich0821** [comment]
请按格式报 bug 并提供足够的复现信息。随时重新打开。
