### ISSUE TITLE
[问题] 在哪里下载 wcf.exe

### ISSUE THREAD

**Issue by CliffHan** [lich0821/WeChatFerry#207]
需要说明的是，我是第一次使用 WechatFerry，对历史情况不太了解，如有冒犯，请见谅。

我看 rust client 代码时看到，WeChat::new() 中实际上是在调用 wcf.exe 进行注入。
但我看了 release 中 v39.2.4 的所有下载，v39.2.4.zip 中只有 sdk.dll/spy.dll/spy_debug.dll。源码目录我也看了一遍，没找到 wcf.exe 这个文件。

我想问一下这个文件应该从哪里获取，是需要使用 vs studio 工程自己编译吗？

谢谢。

**Comment by lich0821** [comment]
`v39.2.x` 后不再需要 `wcf.exe`，详情可以看代码。

**Comment by CliffHan** [comment]
仔细看了一下理解了，现在是以 sdk.dll 方式提供的注入，也就是说 rust client 的例子代码已经过时了。这样大概实现思路就有了，感谢。

**Comment by sunnysab** [comment]
有一年没有用 wcf 了，踩了一点坑。按照楼上的说明，在这个 [commit](https://github.com/lich0821/WeChatFerry/commit/a9e31cf65a45f615d8880d8c601e34771fdb58b5) 中找到了对 sdk 调用的代码。同时，注入部分在 injector.cpp 的 EjectDll 函数中。

其实还是希望能提供一个 wcf.exe 注入工具，方便 Python 机器人与 wcf 分离在两台设备上。在当前模式下，尽管用 wcf-client-rust 等项目将 http 接口暴露出来对架构来说更方便，但苦于没有针对这些 http 接口的 wrapper，需要自己写更多的代码。

**Comment by sunnysab** [comment]
写了一个 loader，供参考。

```python
import ctypes
import os.path


class Wcf:

    DEFAULT_SDK_PATH = 'binary/sdk.dll'

    def __init__(self):
        pass

    def load(self, debug:bool=False, port:int=10086):
        if not os.path.exists(self.DEFAULT_SDK_PATH):
            print('SDK 不存在！')

        self.sdk = ctypes.cdll.LoadLibrary(self.DEFAULT_SDK_PATH)
        # 初始化 SDK. 出现错误时，SDK 会调用 MessageBox 弹窗提示错误信息并返回 -1
        if self.sdk.WxInitSDK(debug, port) != 0:
            exit(-1)

    def cleanup(self):
        if self.sdk.WxDestroySDK() != 0:
            print('退出失败！')

if __name__ == '__main__':
    wcf = Wcf()
    wcf.load()
    input('Press Enter to exit...')
    wcf.cleanup()
```
