### ISSUE TITLE
[🐛BUG] Go Http客户端无法保存朋友圈消息到数据库

### ISSUE THREAD

**Issue by alva1211** [lich0821/WeChatFerry#208]
**描述这个 bug**
发起刷新朋友圈api请求后，终端中出现如下错误。无法将朋友圈消息保存到message表。
![image](https://github.com/user-attachments/assets/260ef8ef-63aa-490f-ad51-821e460486c0)

**Comment by lich0821** [comment]
什么客户端？如何复现？

**Comment by alva1211** [comment]
wechatFerry 的 go版本http端: https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/README.MD
调用他的刷新朋友圈接口后，就会报上面提到的错误

**Comment by lich0821** [comment]
> wechatFerry 的 go版本http端: https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/README.MD 1、使用3.9.2.23版本微信pc端登录微信 2、打开wrest.exe 3、调用wrest提供的刷新朋友圈接口后，就会报上面提到的错误

[go_wcf_http](https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/README.MD)和`wrest.exe`是两个东西吧？

**Comment by alva1211** [comment]
> > wechatFerry 的 go版本http端: https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/README.MD 1、使用3.9.2.23版本微信pc端登录微信 2、打开wrest.exe 3、调用wrest提供的刷新朋友圈接口后，就会报上面提到的错误
> 
> [go_wcf_http](https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/README.MD)和`wrest.exe`是两个东西吧？

是的

**Comment by lich0821** [comment]
为啥不用同一套呢？

**Comment by alva1211** [comment]
> 为啥不用同一套呢？

说错了不好意思 https://github.com/lich0821/WeChatFerry/blob/master/clients/gohttp/README.md
是上面这个项目。
![image](https://github.com/user-attachments/assets/fdaf55e2-ad2a-4f87-a1fb-93453feb74b4)

**Comment by lich0821** [comment]
可以提到 [wrest](https://github.com/opentdp/wrest-chat/issues)，大佬解决问题会更快。
