### ISSUE TITLE
[问题] roomdata.proto 相关

### ISSUE THREAD

**Issue by CliffHan** [lich0821/WeChatFerry#209]
我看到有些客户端代码里面有 roomdata.proto，比如：https://github.com/lich0821/WeChatFerry/blob/master/clients/rust/wcferry/proto/roomdata.proto

但我在源码里面又没有看到这个 proto，我看的目录是这里：https://github.com/lich0821/WeChatFerry/tree/master/WeChatFerry/rpc/proto

所以我想确认一下，是不是这个文件已经不再使用了？谢谢

**Comment by lich0821** [comment]
客户端和（姑且称为）服务端是两个东西。

**Comment by CliffHan** [comment]
我能看明白 roomdata 是 PC 端数据库里的数据，wcf 客户端从 PC 端直接拿到这部分原始数据，然后用 roomdata.proto 去解。
但我不知道为什么这里解析有错。是不是 proto 定义本身就是推测出来的，而推测的格式是有错的？

下面是我的原始数据和报错。

roomdata=[10, 22, 10, 10, 113, 113, 53, 54, 53, 53, 48, 55, 52, 52, 18, 6, 233, 159, 169, 233, 185, 143, 24, 8, 10, 15, 10, 9, 80, 117, 110, 107, 101, 114, 75, 101, 110, 18, 0, 24, 8, 10, 24, 10, 18, 119, 120, 105, 100, 95, 56, 53, 55, 52, 55, 57, 53, 55, 52, 56, 52, 49, 50, 18, 0, 24, 0, 10, 16, 10, 10, 99, 104, 101, 110, 57, 49, 57, 53, 54, 54, 18, 0, 24, 0, 10, 16, 10, 10, 106, 105, 110, 107, 117, 110, 122, 104, 97, 111, 18, 0, 24, 1, 24, 0, 40, 244, 3, 50, 0, 56, 140, 206, 228, 205, 2, 64, 140, 206, 228, 205, 2]

decode_result=Err(DecodeError { description: "invalid wire type: LengthDelimited (expected Varint)", stack: [("RoomData", "field_6")] })

**Comment by CliffHan** [comment]
我把 field_6 改成 string 就可以解析了。

**Comment by lich0821** [comment]
可能这是有朋友反馈获取群成员失败的原因。

**Comment by CliffHan** [comment]
> 可能这是有朋友反馈获取群成员失败的原因。

有可能，我现在是在重写 rust client，是在处理 query_chat_room_info 接口响应时发现的问题。
其他语言情况应该差不多。可以改一下 field_6 试试。
