### ISSUE TITLE
[💡SUG] 最新版的 DLL 求支持 acceptNewFriend

### ISSUE THREAD

**Issue by kenshinlin** [lich0821/WeChatFerry#222]
**你希望添加的功能是否与某个问题相关？**
最新的 DLL 不支持 accept new friend

**描述你希望的解决方案**
支持 acceptNewFriend

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by lich0821** [comment]
Closing this as a duplicate of #200
