### ISSUE TITLE
[💡SUG] 大佬，如何获取群成员昵称

### ISSUE THREAD

**Issue by knight-666** [lich0821/WeChatFerry#224]
目前通过查询库，只能查询到群成员的wxid，无法获取昵称
![image](https://github.com/user-attachments/assets/8560a6da-7d5e-48b5-a15b-42764b86c21d)

RoomData解析出来的数据为
![image](https://github.com/user-attachments/assets/5d177fa2-6ce4-482c-a967-ac6f668b0680)

**Comment by lich0821** [comment]
需要解一下PB，可以去wcfrust提个需求让维护的群友加一下😂

**Comment by knight-666** [comment]
> 需要解一下PB，可以去wcfrust提个需求让维护的群友加一下😂

好的，想问下大佬这个pb，golang应该怎么解，感谢大佬
