### ISSUE TITLE
[🐛BUG] 不能给给企微联系人发送消息

### ISSUE THREAD

**Issue by yuzifu** [lich0821/WeChatFerry#230]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
发送消息接口，当接收人是企微联系人时，对方收不到，微信显示消息在转圈圈

**使用环境（请补全下列信息）:**
- 操作系统：Win11
- 操作系统版本：64位
- Python 版本：3.9 64位

**屏幕截图**
![image](https://github.com/user-attachments/assets/3804f3d0-839c-47a7-bf17-0bd9776d0a64)

**崩溃信息**
无

**Comment by lich0821** [comment]
https://github.com/lich0821/WeChatFerry/issues/66#issuecomment-1727405259
