### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。报告Protocol Error

### ISSUE THREAD

**Issue by gzadigo** [lich0821/WeChatFerry#232]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 报告Protocol Error
- 是否安装后第一次启动就出现？是
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）不能
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？这个不会运行，没有找到

**使用环境（请补全下列信息）:**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】Win10
- 操作系统版本：【32 位 或 64 位】64位
- Python 版本：【如 3.7.9 32 位，3.8.15 64 位 等】3.10

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![error](https://github.com/user-attachments/assets/236f9f57-efce-4f53-a09c-5dd2fe0787e6)

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
无法复现
