### ISSUE TITLE
【求助】我按照文档上说的编译spy和sdk工程，只编译出出来sdk.dll和 spy_debug.dll， spy.dll该如何编译呢？

### ISSUE THREAD

**Issue by x19990416** [lich0821/WeChatFerry#236]
我按照文档上说的编译spy和sdk工程，只编译出出来sdk.dll和 spy_debug.dll， spy.dll该如何编译呢？

![36a54beb327f32d1a51f4ddbf44fb71](https://github.com/user-attachments/assets/1d5713e6-bc65-4687-90cb-7c1175646d4b)
![image](https://github.com/user-attachments/assets/3c4086c0-0977-48c7-a694-6fe2257271b2)

**Comment by lich0821** [comment]
可以使用项目自带的 gitthub action 来编译

**Comment by x19990416** [comment]
编译好了，我是分开用release和debug两个编译环境编译的 T_T不知道有没有问题，然后我想问下，为啥使用了spy.dll程序里面还要用spy_debug.dll呢？不是太理解，另外，在sdk预编译的时候使用的是framework.h 不是通常的pch.h ，希望对于文档能做一点修改，这样子方便新手入手。。我C++是个萌新T_T

**Comment by kingmo888** [comment]
在项目编译时，debug模式下会编译出debug的来。它的作用是，有些代码限制在类似# if DEBUG，release版本会在编译时自动忽略，只在debug版中提示，用于调试。
