### ISSUE TITLE
[🐛BUG] 文件名错误

### ISSUE THREAD

**Issue by x6nux** [lich0821/WeChatFerry#237]
https://github.com/lich0821/WeChatFerry/blob/master/clients/go_wcf_http/mian.go

**Comment by lich0821** [comment]
你能看懂这个 `BUG` 么？看不懂的话你关掉吧 @yitiaoaishuijiaodexianyu

**Comment by yitiaoaishuijiaodexianyu** [comment]
啥文件名BUG 没看懂- -

**Comment by CliffHan** [comment]
我猜他的意思应该是那个源文件 mian.go 应该是 main.go。

**Comment by yitiaoaishuijiaodexianyu** [comment]
@CliffHan 6 我都没发现 无所谓 反正不影响使用

**Comment by lich0821** [comment]
> @CliffHan 6 我都没发现 无所谓 反正不影响使用

咱有点追求吧～
