### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by YuanKyL** [lich0821/WeChatFerry#244]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
- 是否安装后第一次启动就出现？
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？

**使用环境（请补全下列信息）:**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：【32 位 或 64 位】
- Python 版本：【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）
![image](https://github.com/user-attachments/assets/fb182a1d-ebdc-4638-8800-e7ca5f8c1cf7)

**Comment by lich0821** [comment]
#239
