### ISSUE TITLE
运行示例 python main.py 出现弹窗错误

### ISSUE THREAD

**Issue by YuanKyL** [lich0821/WeChatFerry#245]
**使用环境（请补全下列信息）:**
- 操作系统：【Windows 10】
- 操作系统版本：【4 位】
- Python 版本：【3.10】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

![image](https://github.com/user-attachments/assets/086e72c0-abbc-41c0-841e-24a9103696b9)
![image](https://github.com/user-attachments/assets/d236db2d-b560-4aba-ac9c-305ca141b2fe)
![image](https://github.com/user-attachments/assets/a0e153f1-f96c-4356-9c7c-111c51953d04)
，求大佬解答

**Comment by longcpu** [comment]
我也出现同样的错误了,希望大佬能解答,顺便问问有Q群之类的地方一起探讨吗?

**Comment by lich0821** [comment]
Closing this as a duplicate of #244

**Comment by YuanKyL** [comment]
已经解决
&nbsp;


7号
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月28日(星期六) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lich0821/WeChatFerry] 运行示例 python main.py 出现弹窗错误 (Issue #245)














 
Closed #245 as completed.
