### ISSUE TITLE
[🐛BUG] 无法撤回消息

### ISSUE THREAD

**Issue by shaojiankui** [lich0821/WeChatFerry#247]
从MSG0.db的MSG表中查IsSender = 1的，也就是机器人自己发的消息。拿到2分钟以内发的消息后，调用
id = msg.get('MsgSvrID')
wcf.revoke_msg(id)
一直返回-1，从来没成功过，也没有错误日志。
重启微信也无法解决。

**使用环境:**
- 操作系统：【Windows Server 2022】
- 操作系统版本：【64 位】
- Python 版本：【3.8.6 64 位 】
- wcferry==39.2.4.0
- wechat 3.9.10.27

**Comment by lich0821** [comment]
https://github.com/lich0821/WeChatFerry/issues/196#issuecomment-2269332651
