### ISSUE TITLE
下载群聊文件时 download_attach 失效

### ISSUE THREAD

**Issue by 15639812795** [lich0821/WeChatFerry#250]
我使用的是python
如果文件名为英文，接口会返回下载成功，但实际本地没有该文件
![jt](https://github.com/user-attachments/assets/f581ae0a-101e-458c-a1d1-25e370694e8a)

如果文件名为中文，接口会直接崩溃，程序中断
![jt02](https://github.com/user-attachments/assets/d068ce01-7b6e-4ff5-90a3-ee716a1fc751)

**Comment by lich0821** [comment]
不要直接使用 `download_attach `，除非你知道自己在干什么。

**Comment by 15639812795** [comment]
> 不要直接使用 `download_attach `，除非你知道自己在干什么。

我想接收客户群聊里发的文件，如果我把微信设置里的自动下载关闭，但当文件大于200M以后，就不能下载成功了
