### ISSUE TITLE
[🐛BUG] 有时候nng连接上了但收不到消息，发送消息无影响

### ISSUE THREAD

**Issue by HenryXiaoYang** [lich0821/WeChatFerry#254]
**描述这个 bug**
试过wcferry python客户端，自己手写客户端，都会出现有时候nng连接上了但是接收不到消息的情况。但是发送消息，请求数据（如wxid）无问题。

```python
with pynng.Pair1() as sock:
    sock.dial(msg_url, block=True)  # True，成功连接上了
    while True:
        print(rsp.ParseFromString(sock.recv_msg(block=True).bytes)) # 连接后有可能接收不到任何消息
```

希望增加websocket，稳定性可维护性会提高很多，调用起来也方便。

**使用环境（请补全下列信息）:**
- 操作系统：Win10试过，docker+macos试过，纯docker也试过
- 操作系统版本：64
- Python 版本：3.9

**屏幕截图**
不适用

**崩溃信息**
不适用

**Comment by lich0821** [comment]
无法复现
