### ISSUE TITLE
vs无法正确加载项目，缺少 `#include "MinHook.h"`

### ISSUE THREAD

**Issue by aohanhongzhi** [lich0821/WeChatFerry#257]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 什么问题？
初次工程加载
- 是否安装后第一次启动就出现？

![image](https://github.com/user-attachments/assets/32ac4ba9-18e9-434b-9527-57647d3ddc5e)

- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？

**使用环境（请补全下列信息）:**
- 操作系统：【如 Windows 7, Windows 10, Windows Server 2008 等】
- 操作系统版本：【32 位 或 64 位】
- Python 版本：【如 3.7.9 32 位，3.8.15 64 位 等】

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
🚫 非开发用户不需要往下看。 开发用户：可以根据文档和错误提示，自行解决编译错误的人员。
