### ISSUE TITLE
[🐛BUG] go client问题 , connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by leo94666** [lich0821/WeChatFerry#259]
**描述这个 bug**
下载源代码，编写main，直接运行go客户端，报错
```
package main

import (
	"github.com/danbai225/WeChatFerry-go/wcf"
)

func main() {
	c, err := wcf.NewWCF("")
	if err != nil {
		panic(err)
	}
	println(c.IsLogin())
}

```

报错

```
GOROOT=D:\env\go #gosetup
GOPATH=C:\Users\licod\go #gosetup
GOPROXY=https://goproxy.cn,direct #gosetup
D:\env\go\bin\go.exe build -o C:\Users\licod\AppData\Local\JetBrains\GoLand2024.2\tmp\GoLand\___go_build_github_com_danbai225_WeChatFerry_go.exe github.com/danbai225/WeChatFerry-go #gosetup
C:\Users\licod\AppData\Local\JetBrains\GoLand2024.2\tmp\GoLand\___go_build_github_com_danbai225_WeChatFerry_go.exe #gosetup
panic: dial tcp 127.0.0.1:10086: connectex: No connection could be made because the target machine actively refused it.

goroutine 1 [running]:
main.main()
	D:/leon/WeChatFerry/WeChatFerry-39.2.4/clients/go/main.go:10 +0x5c

Process finished with the exit code 2
```

**使用环境（请补全下列信息）:**
- 操作系统：window 11  23H2
- 操作系统版本：【64 位】
- Go版本：go version go1.23.2 windows/amd64

**崩溃信息**
![image](https://github.com/user-attachments/assets/d623c4f0-ec04-4772-9a9e-9f0287f3c283)
端口出入站规则已开、防火墙已关
![image](https://github.com/user-attachments/assets/a3e57e41-599c-4303-afd7-7efd997d1bba)

**Comment by lich0821** [comment]
凭这些信息，能定位这个 `BUG` 不？ @danbai225

**Comment by leo94666** [comment]
> 凭这些信息，能定位这个 `BUG` 不？ @danbai225

有什么需要的，可以及时和我群里沟通。

**Comment by leo94666** [comment]
补充一下，以上是go client问题，go_wcf_http也有问题，它的问题应该是go client衍生的
go_wcf_http的问题如下：
![image](https://github.com/user-attachments/assets/36993dbc-6709-4c86-bde2-6f92b2b12384)

**Comment by danbai225** [comment]
我最近可能没有时间看 这个项目我很久没更新了不确定是不是协议发生了变化 你可以看看欢迎pr





补充一下，以上是go client问题，go_wcf_http也有问题，它的问题应该是go client衍生的
go_wcf_http的问题如下：
image.png (view on web)

**Comment by leo94666** [comment]
> 我最近可能没有时间看 这个项目我很久没更新了不确定是不是协议发生了变化 你可以看看欢迎pr 补充一下，以上是go client问题，go_wcf_http也有问题，它的问题应该是go client衍生的 go_wcf_http的问题如下： image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

嗷嗷，有木有原理文档或者博客看看，我自己研究研究

**Comment by yitiaoaishuijiaodexianyu** [comment]
https://www.topgoer.com/go基础/

**Comment by danbai225** [comment]
把最新的protocol协议复制过去 用生成工具生成以下就行 这些可以搜 proto golang生成
go客户端主要就是rpc调用不存在什么逻辑代码

**Comment by yitiaoaishuijiaodexianyu** [comment]
> > 我最近可能没有时间看 这个项目我很久没更新了不确定是不是协议发生了变化 你可以看看欢迎pr 补充一下，以上是go client问题，go_wcf_http也有问题，它的问题应该是go client衍生的 go_wcf_http的问题如下： image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 嗷嗷，有木有原理文档或者博客看看，我自己研究研究
go版本 请使用go.mod中的go 1.21.5   然后执行go mod tidy 并且安装mingw64(新版用到了cgo) 
https://www.topgoer.com/go基础/  https://www.topgoer.com/gin框架/

**Comment by yitiaoaishuijiaodexianyu** [comment]
> 把最新的protocol协议复制过去 用生成工具生成以下就行 这些可以搜 proto golang生成 go客户端主要就是rpc调用不存在什么逻辑代码

他没有写调用wcf.exe 启动 仅仅是运行了go的代码而已 go client 不存在bug问题  go_wcf_http以go client为基础新增http接口功能 32位微信时是调用wcf.exe  64位微信时为cgo调用sdk.dll  他的go环境配置有问题
