### ISSUE TITLE
[💡SUG] 能否打成 Docker 镜像

### ISSUE THREAD

**Issue by EniacTNB** [lich0821/WeChatFerry#26]
**你希望添加的功能是否与某个问题相关？**
感谢，不知道是否可以连底层的PC一起打个docker image，否则再服务端不太好部署

**Comment by lich0821** [comment]
Hello，目前没有计划，使用Windows Server还是比较方便的，群里大多机器人这么跑（还有些跑在NAS的虚拟机上）。

**Comment by danni-cool** [comment]
我已经完成了这个打包和测试，https://github.com/danni-cool/wechatbot-provider-windows
