### ISSUE TITLE
[💡SUG] 最新的版本39.3.2.0 对应的微信版本是多少啊？目测3.9.10.27不行，有报错······ 感谢大佬

### ISSUE THREAD

**Issue by dami1018** [lich0821/WeChatFerry#267]
最新的版本39.3.2.0 对应的微信版本是多少啊？目测3.9.10.27不行，有报错······ 感谢大佬

**Comment by yuzifu** [comment]
3.9.11.25

**Comment by wolfrun001** [comment]
我用 39.3.3.1 使用下载的微信 3.9.11.25 ,提示不支持当前版本

**Comment by ZYong9908** [comment]
> 我用 39.3.3.1 使用下载的微信 3.9.11.25 ,提示不支持当前版本

同样的 39.3.3.0用3.9.11.25是正常的，升级到 39.3.3.1 提示不支持当前版本
