### ISSUE TITLE
图片类型的消息转发不了？

### ISSUE THREAD

**Issue by fuli66** [lich0821/WeChatFerry#273]
图片类型的消息不能转发，并且图片不能自动缓存到本地，图片没有办法下载到本地。

**Comment by wuhao1477** [comment]
可以的，py项目的话可以 [参考这里](https://github.com/HenryXiaoYang/XYBot/blob/main/wcferry_helper/wcferry_helper.py#L150)

**Comment by fuli66** [comment]
> 可以的，py项目的话可以 [参考这里](https://github.com/HenryXiaoYang/XYBot/blob/main/wcferry_helper/wcferry_helper.py#L150)
我是 windows 客户端程序，有 10010 端口的接口
