### ISSUE TITLE
[💡SUG] 表情包下载

### ISSUE THREAD

**Issue by xy3xy3** [lich0821/WeChatFerry#284]
**你希望添加的功能是否与某个问题相关？**
最近做了一个机器人总结群消息，已经支持了图片，文字
https://github.com/SYSUMSC/wxqunBot
希望能够支持表情包的读取方便总结

**描述你希望的解决方案**
提供一个函数下载表情包
。

**Comment by xy3xy3** [comment]
我想复杂了,cdnurl可以直接下载

**Comment by liuzixiao666** [comment]
cdnurl是什么，我使用旧版的download_image一直报错

**Comment by MarushiruDonato** [comment]
> cdnurl是什么，我使用旧版的download_image一直报错

如果是表情包WxMsg的content内容是一个下面这样的xml
```xml
<msg>
    <emoji fromusername=""
           tousername=""
           type="2"
           idbuffer="media:0_0"
           md5="b6b54c2e12f17e7ca5bbafd2ef9d1765"
           len="19208"
           productid=""
           androidmd5=""
           androidlen="19208"
           s60v3md5=""
           s60v3len="19208"
           s60v5md5=""
           s60v5len="19208"
           cdnurl="http://vweixinf.tc.qq.com/110/20401/stodownload?m=b6b54c2e12f17e7ca5bbafd2ef9d1765&amp;filekey=3043020101042f302d02016e040253480420623662353463326531326631376537636135626261666432656639643137363502024b08040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad58560009930e485380830000006e01004fb153480e38e1b156bd64392&amp;ef=1&amp;bizid=1022"
           designerid=""
           thumburl=""
           encrypturl="http://vweixinf.tc.qq.com/110/20402/stodownload?m=4d22d502f125302abe1fa9711b2debec&amp;filekey=3043020101042f302d02016e040253480420346432326435303266313235333032616265316661393731316232646562656302024b10040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad5856000a2b9f485380830000006e02004fb253480e38e1b156bd6439e&amp;ef=2&amp;bizid=1022"
           aeskey=""
           externurl="http://vweixinf.tc.qq.com/110/20403/stodownload?m=14b3b827fe58326af16998941ef24925&amp;filekey=3043020101042f302d02016e040253480420313462336238323766653538333236616631363939383934316566323439323502020c90040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad5856000ac7fa485380830000006e03004fb353480e38e1b156bd643a5&amp;ef=3&amp;bizid=1022"
           externmd5="" width="298" height="300" tpurl="" tpauthkey="" attachedtext="" attachedtextcolor="" lensid="" emojiattr="" linkid=""
           desc=""/>
</msg>
```

cdnurl里面的`&amp;`替换成`&`
就得到了
```
http://vweixinf.tc.qq.com/110/20401/stodownload?m=b6b54c2e12f17e7ca5bbafd2ef9d1765&filekey=3043020101042f302d02016e040253480420623662353463326531326631376537636135626261666432656639643137363502024b08040d00000004627466730000000132&hy=SH&storeid=267ad58560009930e485380830000006e01004fb153480e38e1b156bd64392&ef=1&bizid=1022
```
直接下载这个链接内容, 然后把后缀改成对应的图片格式, 比如`gif`或者'jpg'就能得到图片了

**Comment by liuzixiao666** [comment]
> > cdnurl是什么，我使用旧版的download_image一直报错
> 
> 如果是表情包WxMsg的content内容是一个下面这样的xml
> 
> <msg>
>     <emoji fromusername=""
>            tousername=""
>            type="2"
>            idbuffer="media:0_0"
>            md5="b6b54c2e12f17e7ca5bbafd2ef9d1765"
>            len="19208"
>            productid=""
>            androidmd5=""
>            androidlen="19208"
>            s60v3md5=""
>            s60v3len="19208"
>            s60v5md5=""
>            s60v5len="19208"
>            cdnurl="http://vweixinf.tc.qq.com/110/20401/stodownload?m=b6b54c2e12f17e7ca5bbafd2ef9d1765&amp;filekey=3043020101042f302d02016e040253480420623662353463326531326631376537636135626261666432656639643137363502024b08040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad58560009930e485380830000006e01004fb153480e38e1b156bd64392&amp;ef=1&amp;bizid=1022"
>            designerid=""
>            thumburl=""
>            encrypturl="http://vweixinf.tc.qq.com/110/20402/stodownload?m=4d22d502f125302abe1fa9711b2debec&amp;filekey=3043020101042f302d02016e040253480420346432326435303266313235333032616265316661393731316232646562656302024b10040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad5856000a2b9f485380830000006e02004fb253480e38e1b156bd6439e&amp;ef=2&amp;bizid=1022"
>            aeskey=""
>            externurl="http://vweixinf.tc.qq.com/110/20403/stodownload?m=14b3b827fe58326af16998941ef24925&amp;filekey=3043020101042f302d02016e040253480420313462336238323766653538333236616631363939383934316566323439323502020c90040d00000004627466730000000132&amp;hy=SH&amp;storeid=267ad5856000ac7fa485380830000006e03004fb353480e38e1b156bd643a5&amp;ef=3&amp;bizid=1022"
>            externmd5="" width="298" height="300" tpurl="" tpauthkey="" attachedtext="" attachedtextcolor="" lensid="" emojiattr="" linkid=""
>            desc=""/>
> </msg>
> cdnurl里面的`&amp;`替换成`&` 就得到了
> 
> ```
> http://vweixinf.tc.qq.com/110/20401/stodownload?m=b6b54c2e12f17e7ca5bbafd2ef9d1765&filekey=3043020101042f302d02016e040253480420623662353463326531326631376537636135626261666432656639643137363502024b08040d00000004627466730000000132&hy=SH&storeid=267ad58560009930e485380830000006e01004fb153480e38e1b156bd64392&ef=1&bizid=1022
> ```
> 
> 直接下载这个链接内容, 然后把后缀改成对应的图片格式, 比如`gif`或者'jpg'就能得到图片了

爸爸！！！！！
