### ISSUE TITLE
[💡SUG]关于wxMsg类只有sender wxid只有 rec wixd的问题

### ISSUE THREAD

**Issue by niskeye** [lich0821/WeChatFerry#29]
if (roomid.find("@chatroom") != string::npos) { // 群 ID 的格式为 xxxxxxxxxxx@chatroom
        wxMsg.is_group = true;
        wxMsg.roomid   = roomid;
        if (wxMsg.is_self) {
            wxMsg.sender = GetSelfWxid();
        } else {
            wxMsg.sender = GetStringByAddress(*p + g_WxCalls.recvMsg.wxId);
        }
    } else {
        wxMsg.is_group = false;
        if (wxMsg.is_self) {
            wxMsg.sender = GetSelfWxid();
        } else {
            wxMsg.sender = roomid;
        }
    }
请问下，消息不是应该有个 发送者的ID和一个接收者的ID吗？ 运行的时候如果是自己手机端发的消息，就只有sender是自己的wxid。PC端就不知道是发给谁的了,这个问题是在编wxMsg这个类时,没有设计接收发送者wxid和接收者wxid？还是说原始的消息体就只有这样的结构？
看了下spy的注释，是说私聊的时候 wxid 本来就是空的，那于客户端显示的时候，怎么知道是谁的消息？

**Comment by RedRiverCN** [comment]
私聊消息，如果是自己发送的is_self=true，代码硬编码为自己的wxid
if (wxMsg.is_self) {
wxMsg.sender = GetSelfWxid();
} 
，这样该条消息无法知道对方的wxid;

**Comment by lich0821** [comment]
这是你自己发的，“对方”难道不是你自己吗？

**Comment by lich0821** [comment]
太久没更新，先关闭。
