### ISSUE TITLE
rust编译提示找不到‘protoc’

### ISSUE THREAD

**Issue by v200123** [lich0821/WeChatFerry#30]
编译这个项目的rust版本，一直提示

--- stdout
  cargo:rerun-if-changed=proto/wcf.proto
  cargo:rerun-if-changed=.
  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.
  For more information: https://docs.rs/prost-build/#sourcing-protoc

windows已经安装了基本环境，rust也加入了protobuf的引用，但还是提示这个，请问你是怎么编译的呀

**Comment by lich0821** [comment]
@supermoonie 可以帮忙看一下不？

**Comment by supermoonie** [comment]
![image](https://user-images.githubusercontent.com/17509860/240754667-fcaf2e2b-76cc-4516-b87c-5533e56518fd.png)

缺少以下步骤

**Comment by v200123** [comment]
> ![image](https://user-images.githubusercontent.com/17509860/240754667-fcaf2e2b-76cc-4516-b87c-5533e56518fd.png)
> 
> 缺少以下步骤


这一步已经执行过了，下面是安装后的提示，或许和我rust通过vscode的终端安装的有关？
![image](https://github.com/lich0821/WeChatFerry/assets/29189439/04e6bf70-3e66-45cb-8a9d-fc78adbf3dc0)

**Comment by v200123** [comment]
问题的原因在tonic的issue找到了这是链接：
https://github.com/hyperium/tonic/issues/1047
降级到0.7就好了
