### ISSUE TITLE
没有获取群列表功能  关联不上

### ISSUE THREAD

**Issue by 442830589** [lich0821/WeChatFerry#31]
**你希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述你希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by lich0821** [comment]
> 群列表不是通讯录里面的吗？群的wxid是有特征的，可以过滤一下。

是的，可以通过get_contacts获取，`@chatroom`结尾的就是群聊。
