### ISSUE TITLE
autoAcceptFriendRequest方法，v3、v4、scene均有值，在调用wcf.accept_new_friend后进入except中，

### ISSUE THREAD

**Issue by q78670540** [lich0821/WeChatFerry#32]
autoAcceptFriendRequest方法，v3、v4、scene均有值，在调用wcf.accept_new_friend后进入except中：

同意好友出错：Protocol message Verification has no "scene" field.

**Comment by q78670540** [comment]
同意好友出错：Protocol message Verification has no "scene" field.

**Comment by q78670540** [comment]
`<msg fromusername="ggg_ggggggggggg" encryptusername="v3_020b3826fd030100000000008f11350d7b93dd000000501ea9a3dba12f95f6b60a0536a1adb611471b839d55111569b888c9c6bcddeab83a376986034533781408170939ea75e27c90c015733b399d901c75b0@stranger" fromnickname="山鬼不识字" content="我是山鬼不识字" fullpy="shanguibushizi" shortpy="SGBSZ" imagestatus="3" scene="30" country="" province="" city="" sign="" percard="0" sex="1" alias="ZZZhao_HaHa" weibo="" albumflag="0" albumstyle="0" albumbgimgid="" snsflag="273" snsbgimgid="http://shmmsns.qpic.cn/mmsns/4WnLFLz2ia6Zrs9ZCWBaKtsaiaExCr50kKzFA3cGiaMrdgEyiaERpJKylliceIDndnQHYngTKdkCByCU/0" snsbgobjectid="14101357740064379524" mhash="cbdef6e0ff2335a308ebcdb76d658c3c" mfullhash="cbdef6e0ff2335a308ebcdb76d658c3c" bigheadimgurl="http://wx.qlogo.cn/mmhead/ver_1/C0icWibHASYzqpLtsd4CBXPQchTgibq7kFSQXTtlWCwXqkVw2urvcTVddbk5MJyYPzpcFvtG9J3TgNNv1mGyl70YA/0" smallheadimgurl="http://wx.qlogo.cn/mmhead/ver_1/C0icWibHASYzqpLtsd4CBXPQchTgibq7kFSQXTtlWCwXqkVw2urvcTVddbk5MJyYPzpcFvtG9J3TgNNv1mGyl70YA/132" ticket="v4_000b708f0b0400000100000000007537a6ee7e68218f000d0e5a70641000000050ded0b020927e3c97896a09d47e6e9e4c4ccb7f324e4d59ffb4d2bec71bd68be6b9c5a4241ea1be184b0db07b56f570f12383f7396d3685ea2c20d16ff49701f0ee12fe0abad9b8a0bab798ca19909a9669a913bd2e0a929c49b271e88f5b9c72129cd6d9cfa81c9841f097d2e5e5129699f50493c17aee69@stranger" opcode="2" googlecontact="" qrticket="" chatroomusername="" sourceusername="" sourcenickname="" sharecardusername="" sharecardnickname="" cardversion="" extflag="0"><brandlist count="0" ver="793149915"></brandlist></msg>`

**Comment by lich0821** [comment]
请提供环境、客户端、版本等信息

**Comment by q78670540** [comment]
> 请提供环境、客户端、版本等信息

微信：3.7.0.30

**Comment by lich0821** [comment]
> > 请提供环境、客户端、版本等信息
> 
> 微信：3.7.0.30 wcfhttp：37.1.25.4 python：3.11.2 不好意思，我这边能想到的版本信息是这些了，麻烦问下还需要什么信息嘛？

还有`wcferry`的版本，很可能是它太“老”了

**Comment by q78670540** [comment]
wcferry：__version__ = "37.1.25.2"

**Comment by lich0821** [comment]
> wcferry：**version** = "37.1.25.2"

看起来版本没有问题，你这版本有过变更吗？
你试试重新建一个（虚拟）环境，再安装`wcfhttp`试试，看问题是否存在。如果还存在，提供一下调用参数（建议做一下脱敏）。

**Comment by q78670540** [comment]
好的，我按照你说的试试，先感谢，谢谢你

**Comment by lich0821** [comment]
37.1.25.3已修复，可以验证一下：
```sh
pip install --upgrade wcferry
```
