### ISSUE TITLE
[💡SUG] wcf.exe 可以新增一个 --pid 参数来指定 wechat进程吗？

### ISSUE THREAD

**Issue by mgttt** [lich0821/WeChatFerry#33]
**描述你希望的解决方案**
增加一个wcf.exe 增加一个 pid 参数，用于可以指定WeChat.exe的进程

**描述你考虑的替代方案**
无

**其他**
目前如果系统有多开，会因为打不对进程而失败。。。

**Comment by lich0821** [comment]
多开快搞完，但最后还是废弃了——需要多开的，通常是要搞事情的，那直接花钱买协议比较好。

**Comment by phpmac** [comment]
mac上会失败，

```
2023-06-06 06:36:35,162 没有设置接收消息回调，消息直接通过日志打印；请通过 --cb 设置消息回调
2023-06-06 06:36:35,163 回调接口规范参考接收消息回调样例：http://0.0.0.0:9999/docs
2023-06-06 06:36:35,163 wcferry version: 37.1.25.2
sh: /Users/a/Downloads/fastapi/venv/lib/python3.11/site-packages/wcferry\wcf.exe: No such file or directory
2023-06-06 06:36:35,166 初始化失败！

```

**Comment by lich0821** [comment]
> mac上会失败，
> 
> ```
> 2023-06-06 06:36:35,162 没有设置接收消息回调，消息直接通过日志打印；请通过 --cb 设置消息回调
> 2023-06-06 06:36:35,163 回调接口规范参考接收消息回调样例：http://0.0.0.0:9999/docs
> 2023-06-06 06:36:35,163 wcferry version: 37.1.25.2
> sh: /Users/a/Downloads/fastapi/venv/lib/python3.11/site-packages/wcferry\wcf.exe: No such file or directory
> 2023-06-06 06:36:35,166 初始化失败！
> ```
> 
> 怎么解决

简单来说，只支持 Windows。
