### ISSUE TITLE
[💡SUG]我自己发送给别人的消息，程序里面为啥收不到啊？

### ISSUE THREAD

**Issue by ruocaoqing** [lich0821/WeChatFerry#34]
我自己发送给别人的消息，程序里面为啥收不到啊？

**Comment by Xiaeer** [comment]
确实有这个问题，我刚发现，自己发送的信息收不到

**Comment by lich0821** [comment]
😂因为PC端发出去的消息不会再发回来PC端；但手机端发的会，因为需要同步到PC端。
非要实现的话，可以Hook发消息Call，发消息的时候存一下。

**Comment by Xiaeer** [comment]
> 

好的，谢谢大佬，确实是这个问题，pc自己发的不走本地，手机端发的pc会同步
