### ISSUE TITLE
建议添加功能发送的图片可以直接是base64

### ISSUE THREAD

**Issue by yuan199696** [lich0821/WeChatFerry#37]
建议添加功能发送的图片可以直接是base64，而不只是支持路径

**Comment by lich0821** [comment]
能否提供几个样例数据供测试？

**Comment by yuan199696** [comment]
https://github.com/yuan199696/test_base64_1/blob/main/base64_1

里面有两个base64的文件，都是stable-diffusion-webui生成的图片

![image](https://github.com/lich0821/WeChatFerry/assets/32838333/f1f3960e-c8ae-4538-9c2f-251e6b04cbfb)

**Comment by LeanFly** [comment]
其实吧，拿到sd的base64了，用python的临时文件搭个桥就可以了。
