### ISSUE TITLE
[💡SUG]希望作者可以添加屏蔽某些群聊以及公众号消息的功能

### ISSUE THREAD

**Issue by yuan199696** [lich0821/WeChatFerry#39]
今天发现一个问题，控制台显示接收了公众号的推送消息后，群聊的消息被吞掉了，并没有打印出来，继续观察，出现了两次这样的问题，群成员在发送消息的瞬间恰好接收到了公众号的消息，造成了该群成员的消息被吞掉了！
希望作者可以增加功能：
1、屏蔽指定群聊消息、屏蔽指定公众号信息
2、踢除指定群成员（一些群成员发送广告或者hs内容）

**Comment by yuan199696** [comment]
1、屏蔽指定群聊消息、屏蔽指定公众号信息。这个功能我已实现

**Comment by lich0821** [comment]
> 1、屏蔽指定群聊消息、屏蔽指定公众号信息。这个功能我已实现

是怎么个屏蔽法呢？

踢人在预览版里已经有了，现在1群我给加上了，有个画画机器人老刷屏。

**Comment by yuan199696** [comment]
> 

直接反向操作，只打印指定roomid的群聊消息，哈哈

**Comment by lich0821** [comment]
> > 
> 
> 直接反向操作，只打印指定roomid的群聊消息，哈哈

🤣这是不是掩耳盗铃
