### ISSUE TITLE
python版启动报错：Error parsing message

### ISSUE THREAD

**Issue by evekcin** [lich0821/WeChatFerry#4]
该项目之前曾多次正常启动，但是大部分情况启动异常。
今天同一个微信号、多台设备（win10虚拟机+win10物理机）测试后，均报错：

![27161671622436_ pic](https://user-images.githubusercontent.com/1585726/208916190-d49372d8-f69d-4ade-af41-698612b72caa.jpg)

**Comment by lich0821** [comment]
从日志来看是反序列化异常，猜测wxid含有特殊字符或者编码方式比较特别。手上的号无法复现，蹲下一个复现的。

**Comment by lich0821** [comment]
现在自定义了编解码，可以重新试试看看是否已经解决。 @evekcin

**Comment by lich0821** [comment]
先关闭了，如果还有问题再打开。
