### ISSUE TITLE
[💡SUG]希望作者可以增加拦截pc发消息的功能

### ISSUE THREAD

**Issue by yuan199696** [lich0821/WeChatFerry#45]
我的应用场景：我在微信群中通过 WeChatRobot 接入了 stable-diffusion-webui 共大家玩耍文生图，然而我自己想在pc端微信向群里发送文字时并不能被 WeChatRobot 拦截到，经在群里和作者沟通后，明白了还要自己开发拦截pc发消息的功能，但本人试了一天后始终无法解决，希望作者有时间可以加上此功能！

**Comment by jamosnet** [comment]
今天我在测试消息回调时候也发现这个问题了，别人发的消息，自己手机app上发的消息，都可以出现在回调消息里面， 但是pc微信发送的消息，不会出现在回调里面。 

我本来想通过消息回调来保存聊天记录的，因为pc发送的消息丢失，无法实现了。
