### ISSUE TITLE
[🐛BUG] 回调给信息数据不太准确好像

### ISSUE THREAD

**Issue by wxyShine** [lich0821/WeChatFerry#55]
```txt
{thumb='', sign='xxxxxxxx', type=1, roomId='null', content='111', isGroup=false, sender='xxxxxxxxx', isAt=false, xml='<msgsource>
	<silence>1</silence>
	<membercount>4</membercount>
	<signature>v1_fy2iu6Yr</signature>
	<tmp_node>
		<publisher-id></publisher-id>
	</tmp_node>
</msgsource>
', extra='', id='1616667964132650741', isSelf=false, ts=1691552686}
```
这是一个群组消息  isGroup是false， roomId是空

使用的wcfhttp  v39.0.2.1

**Comment by lich0821** [comment]
企业群？

**Comment by wxyShine** [comment]
> 企业群？

普通微信的群聊

**Comment by lich0821** [comment]
什么客户端？版本多少？

**Comment by wxyShine** [comment]
> 什么客户端？版本多少？

下载的github提供的版本
![image](https://github.com/lich0821/WeChatFerry/assets/42802152/27d52c02-2ab2-499e-8605-5a1e935fdadf)

**Comment by lich0821** [comment]
wcferry是什么版本？在启动wcfhttp的时候应该会同时打印这俩的版本信息的。

**Comment by wxyShine** [comment]
![image](https://github.com/lich0821/WeChatFerry/assets/42802152/44866637-fedb-472f-842c-d0620bbcd5e6)


> wcferry是什么版本？在启动wcfhttp的时候应该会同时打印这俩的版本信息的。

一样的

**Comment by wxyShine** [comment]
找到了 ～是我原因应该～

**Comment by lich0821** [comment]
> 找到了 ～是我原因应该～

啥原因？我正要回复你：
> 我这边没复现出来。你那是偶现还是必现？
