### ISSUE TITLE
[💡SUG] 增加接收群邀请API

### ISSUE THREAD

**Issue by how2fft** [lich0821/WeChatFerry#58]
**描述你希望的解决方案**
![WX20230821-111840](https://github.com/lich0821/WeChatFerry/assets/66544658/83135b2d-f4a8-4308-b960-7a1427bd0436)
找到调用接受群邀请api地址和入参

**其他**
请问如何找到接受群邀请api地址和入参

**Comment by lich0821** [comment]
参考 [https://github.com/lich0821/WeChatFerry/issues/54](https://github.com/lich0821/WeChatFerry/issues/54)
