### ISSUE TITLE
[🐛BUG] 消息转发失败 httpCode 201

### ISSUE THREAD

**Issue by clippers1** [lich0821/WeChatFerry#60]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
- 消息转发失败
- 但是post请求还是能打印body参数

**使用环境（请补全下列信息）:**
- 操作系统：win10
- 操作系统版本：x64
- Python 版本：3.11.3

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![图片](https://github.com/lich0821/WeChatFerry/assets/23101116/894813d8-11a6-4dbf-9c99-447f38e999ba)

**Comment by lich0821** [comment]
这是回调报的错。成功就报200吧，别报其他的。
