### ISSUE TITLE
大佬，请问一下这个项目有没有通过群id获取群成员id的功能？

### ISSUE THREAD

**Issue by processaccou** [lich0821/WeChatFerry#64]
您好，我想问一个问题，这个项目有没有通过群id获取群里所有成员的wxid的功能？

**Comment by lich0821** [comment]
现在的接口没有，但可以通过 sql [1](https://wechatferry.readthedocs.io/zh/latest/autoapi/wcferry/client/index.html#wcferry.client.Wcf.query_sql) / [2](https://wechatferry.readthedocs.io/zh/latest/openapi.html#post--sql) 来实现。

**Comment by processaccou** [comment]
好的，谢谢大佬的神速回复。另外想再问大佬一个问题，关于代码，大佬有没有做一些详细的讲解？

**Comment by clippers1** [comment]
好像没有群昵称

**Comment by lich0821** [comment]
> 好像没有群成员昵称

有的，不过就不是同一张表了，在一个blob类型的字段，是PB编码的群名片。

**Comment by lich0821** [comment]
> 好的，谢谢大佬的神速回复。另外想再问大佬一个问题，关于代码，大佬有没有做一些详细的讲解？

在`chatroom`表里有一个RoomData字段，那里有群名片(PB编码)，没设置的为空，可以回落到昵称；
在`Contact`表里，可以查到昵称，参考 [getAllContacts](https://github.com/lich0821/WeChatRobot/blob/master/robot.py#L181)

**Comment by processaccou** [comment]
感觉大佬是住在github里的，回复的速度是真的快。先感谢大佬这么快就回复了我的问题，但我还有一个问题，就是发送图片，我想通过文件传输助手获取到图片后发送给指定的用户或群聊，但问题是pc端发送的话监听不到消息，手机端发送图片到电脑端能够监听到，但是没有图片文件，请问大佬有什么思路吗？

**Comment by lich0821** [comment]
> 感觉大佬是住在github里的，回复的速度是真的快。先感谢大佬这么快就回复了我的问题，但我还有一个问题，就是发送图片，我想通过文件传输助手获取到图片后发送给指定的用户或群聊，但问题是pc端发送的话监听不到消息，手机端发送图片到电脑端能够监听到，但是没有图片文件，请问大佬有什么思路吗？

（机器人自动回复的）没太理解你这个场景。你都在微信前了，直接发给目标用户就可以了呀，为啥还要文件传输助手再转一道？

**Comment by processaccou** [comment]
我想把文件传输助手作为一个类似于微信机器人的操作页面，然后通过给文件传输助手发送相应的命令，执行相应的功能，其实应该要做一个界面的，但是我不太会写应用程序界面，所以就先拿文件传输助手做文章了。

**Comment by lich0821** [comment]
> 我想把文件传输助手作为一个类似于微信机器人的操作页面，然后通过给文件传输助手发送相应的命令，执行相应的功能，其实应该要做一个界面的，但是我不太会写应用程序界面，所以就先拿文件传输助手做文章了。

那听起来没啥问题。没图片文件是什么个情况？FAQ看了不？

**Comment by processaccou** [comment]
我检查了一下，原来是我理解错了，发送图片后，会有两个dat文件，一个是加密，一个是解密，我把解密路径理解成解密后保存图片的路径了，怪不得一直解密错误，谢谢大佬的解答。

**Comment by lich0821** [comment]
> 我检查了一下，原来是我理解错了，发送图片后，会有两个dat文件，一个是加密，一个是解密，我把解密路径理解成解密后保存图片的路径了，怪不得一直解密错误，谢谢大佬的解答。

两个dat文件，一个是原图，一个是预览图。

**Comment by lich0821** [comment]
> 原来如此，虽然不知道为什么要叫做加密和解密，但是我用着这两个文件确实可以通过大佬的解密接口显示图片。

动作是解密，这个动作是对被`加密`的图片，进行`解密`操作，保存`解密`后的图片。

**Comment by processaccou** [comment]
大佬，我想再问一个问题，就是前面说可以通过sql查询群聊里的用户wxid，但是我不太清楚到底要查找哪张表？

**Comment by lich0821** [comment]
> 大佬，我想再问一个问题，就是前面说可以通过sql查询群聊里的用户wxid，但是我不太清楚到底要查找哪张表？

上面发了，往上翻翻

**Comment by processaccou** [comment]
大佬，请问一下大佬有没有写关于微信数据库的解析，例如哪个数据库有哪些表，有什么数据，我看了上面的发的那两张表，一张是chatroom表，确实有大佬说的roomdata字段，但是我不知道怎么去解析数据，另一张是contact表，但是这张表只能获取账号里的所有好友，无法获取到群里的用户。

**Comment by lich0821** [comment]
这个没有，好多人问，但没人动手。你要不要起个头？大家都补充一下，很快的。

**Comment by lich0821** [comment]
看来又聊跑了一个😂

**Comment by clippers1** [comment]
是不是有的db是加密的，看不到内容

**Comment by lich0821** [comment]
> 是不是有的db是加密的，看不到内容

全部 DB 都是加密的。只是通过微信的会话连接过去，绕过了加密。

看不到内容，具体是什么情况？

**Comment by clippers1** [comment]
比如ChatMsg.db
![图片](https://github.com/lich0821/WeChatFerry/assets/23101116/842a375e-2507-4a72-913b-1eba7d3e1958)

**Comment by lich0821** [comment]
可以看看日志。如果还有问题可以新起一个 ISSUE。
