### ISSUE TITLE
有没有办法在Windows server中多开呢？

### ISSUE THREAD

**Issue by ntdhssz** [lich0821/WeChatFerry#65]
目前尝试过两种办法
1、用两个不同的Windows账号登录并启动wcfhttp，结果是后启动的wcfhttp会提示Call FUNC_IS_LOGIN failed: Timed out
2、使用Sandboxie（沙箱软件），在沙箱中运行两个wcfhttp，结果是后启动的wcfhttp会提示请求超时
有没有其他可行的办法呢？

**Comment by lich0821** [comment]
框架不支持多开。话说，什么场景需要多开机器人呢？

**Comment by ntdhssz** [comment]
嘶，这个思路好诶。没有想要搞事情，只是想一个客服管理多个微信，以及客服间交换管理之类的

**Comment by ntdhssz** [comment]
感谢提供思路。
这里的vine是指wine吗？

**Comment by lich0821** [comment]
见 #80
