### ISSUE TITLE
[🐛BUG] 使用/text接口私聊企微用户时会发送失败

### ISSUE THREAD

**Issue by ntdhssz** [lich0821/WeChatFerry#66]
使用/text接口私聊企微用户时会发送失败

- 操作系统：Windows Server 2006
- 操作系统版本：64 位
- Python 版本：3.10.11

![image](https://github.com/lich0821/WeChatFerry/assets/54196057/d7f45ba4-0398-40b9-aeed-e67db3db9e5f)

红色圈起、处于loading状态的这条信息使用/text发送的，其他都是通过微信客户端和企业微信客户端发送的。

**Comment by lich0821** [comment]
企业微信没测试过，不行的话就是不支持了。
