### ISSUE TITLE
[🐛BUG] get_friends接口会报错，接口里面从字典取值的时候有问题

### ISSUE THREAD

**Issue by pyx-py** [lich0821/WeChatFerry#7]
![Snipaste_2023-03-09_16-53-59](https://user-images.githubusercontent.com/51142411/223970989-fb3e3a23-bb83-4b90-8673-31499ac6c3bb.png)
![Snipaste_2023-03-09_16-54-15](https://user-images.githubusercontent.com/51142411/223971002-d25230ee-a9af-45f5-ae63-22656ef1e028.png)

**Comment by lich0821** [comment]
Fix at this [commit](https://github.com/lich0821/WeChatFerry/commit/0e0ae92afdbfb014556f1fe334b937f0eb7bf401).
