### ISSUE TITLE
[💡SUG] 能不能自动关注公众号，以及获取它的历史消息

### ISSUE THREAD

**Issue by xueyouluo** [lich0821/WeChatFerry#70]
想要在别人分享公众号过来的时候可以自动关注，同时获取某个公众号的历史文章，以及它每天推送的新文章

**Comment by lich0821** [comment]
你这相当于提了三个功能😂

1. 自动关注有待实现。
2. 通过 `call` 获取历史文章有人试过，可能容易被 Ban；之前分享过一个思路，也实现了一个 [工具](https://mp.weixin.qq.com/s/KCchDwkBcO91iH0hgeNfyw)。
3. 接收推着这个已经实现了，已经关注的号的新文章/消息，是可以收到的。
