### ISSUE TITLE
[🐛BUG] 控制台偶尔会卡住不动，敲下回车又正常

### ISSUE THREAD

**Issue by kylinbaozi** [lich0821/WeChatFerry#77]
**描述这个 bug**
wcfhttp，开启了消息转发，有新消息的时候控制台会自动滚屏，但是偶尔会突然卡住不动，需要手动去敲一下回车恢复正常，且恢复正常后中间中断的消息会依次加载...

**使用环境（请补全下列信息）:**
- 操作系统： Windows 10
- 操作系统版本：企业版 64 位
- Python 版本：3.11.5

**屏幕截图**
卡住时截图：
![1](https://github.com/lich0821/WeChatFerry/assets/44959319/f8a90ce1-c22b-445e-a889-1b590cb46a92)
敲回车后滚动了几页的新消息，第一条消息是一个带引用的，不知道是不是因为这条消息导致的
![8](https://github.com/lich0821/WeChatFerry/assets/44959319/976bb047-8c49-4dd9-a6a9-93c39255663e)
但是后续又用带引用的消息测试并没有出现卡住的情况...

**Comment by lich0821** [comment]
![QA](https://github.com/lich0821/WeChatFerry/assets/87742696/16fd84f7-4467-4c7b-9f7b-91f5fd3b6846)
建议给微软提个BUG。

**Comment by kylinbaozi** [comment]
> ![QA](https://user-images.githubusercontent.com/87742696/275371823-16fd84f7-4467-4c7b-9f7b-91f5fd3b6846.jpeg) 建议给微软提个BUG。

非常感谢，我一定管住自己的小手！

**Comment by DreamPuNi** [comment]
或者可以取消控制台的快速编辑模式
