### ISSUE TITLE
[💡SUG] 希望能实现在文件传输助手中@机器人就可以回答我的问题

### ISSUE THREAD

**Issue by hunyanjie** [lich0821/WeChatFerry#78]
希望能实现在文件传输助手中@机器人就可以回答我的问题，并且支持设置只在某几个微信聊天中启用机器人回复功能功能

**Comment by godisboy0** [comment]
老哥，你这个不属于这个项目的支持范围。这个项目只提供通信，功能需要自己开发的。
仅就你这个功能而言，文件传输助手是一个不可登录的账号，你不可能让文件传输助手来回应你~但是如果你登录了一个账号，确实可以收到文件传输助手的消息。但你有这个诉求是要一个账号双端登录？可不建议你拿大号玩机器人。

**Comment by lich0821** [comment]
> 希望能实现在文件传输助手中@机器人就可以回答我的问题，并且支持设置只在某几个微信聊天中启用机器人回复功能功能

见 [WeChatRobot](https://github.com/lich0821/WeChatRobot)。
