### ISSUE TITLE
[💡SUG] 获取微信好友昵称，方便发送信息

### ISSUE THREAD

**Issue by CodeListening** [lich0821/WeChatFerry#8]
有很多好友信息都备注在昵称中，希望能获取该字段

请问在get contracts 的时候能获取微信好友的昵称吗？
如果不能是否在其他的接口中能获取微信好友的昵称呢？

**Comment by lich0821** [comment]
现在已经有昵称了，你说的是备注？

**Comment by lich0821** [comment]
Fixed with commit cc0f2f6fdf41c198379ef33ec454a5a1f814ceab
