### ISSUE TITLE
[💡SUG] 能否让用户指定微信pid用于多开的微信

### ISSUE THREAD

**Issue by DuGuYifei** [lich0821/WeChatFerry#81]
您好，[PR](https://github.com/lich0821/WeChatFerry/pull/80)。
我希望能够指定微信pid，因为有时候我电脑会登录多个微信。请问这个PR有问题吗？或者不合并，可以帮我打个包吗？
我努力过了，总是失败，说我执行proto命令失败。然后我用NuGet的spdlog包有些函数不知道版本是不是不一样，NuGet的包的spdlog里没有一些函数。

**Comment by lich0821** [comment]
可能是配置的问题，我周末抽空编译一版。
先说好，封号了别找我😂

**Comment by DuGuYifei** [comment]
打包成功了

**Comment by godisboy0** [comment]
> 打包成功了

这老哥一看就不是凡品！

**Comment by DreamPuNi** [comment]
老哥打包的文件可以分享吗，我按你代码重新编译报错不行了，那个我记得有个地址我改了也还是不行，QAQ
