### ISSUE TITLE
请问联系人的"标签"不能获得吗？

### ISSUE THREAD

**Issue by Leweibo** [lich0821/WeChatFerry#83]
当前获得的联系人信息：
 {'wxid': '',
  'code': '',
  'remark': '',
  'name': ',
  'country': '',
  'province': '',
  'city': '',
  'gender': ''
}

remark是备注。没有标签信息。微信标签是联系人管理的重要分组手段，请问能否获得标签信息?

**描述你考虑的替代方案**
外接数据库解决，但不能在微信中显示。

**Comment by lich0821** [comment]
查数据库应该可以实现；然后再封装一个方法 `get_tags(wxid)`，实现传入 `wxid` 获取标签。

这个联系人信息字段越加越多了；很多字段又是空的；目前不打算添加了。

**Comment by Leweibo** [comment]
用Remark替代，就是长一点

**Comment by lich0821** [comment]
Remark是备注。

**Comment by Leweibo** [comment]
目前WeChatFerry联系人信息真正有用的其实就是wxid，remark两个字段，强烈建议加入标签字段。

微信联系人信息中remark 和 标签实际上是我们唯一能够在微信中修改的两个字段，目前WeChatFerry中只有一个remark 可用，而remark 一般用于对方真实名字，标签是用来分组的。

至于其他字段，完全没有什么用。

**Comment by lich0821** [comment]
有用没用是看需求的。对于不用机器人的人来说，整个项目完全没有用。

**Comment by Leweibo** [comment]
谢谢
不好意思，刚用1天，很多东西不清楚。

解决方法很简单：
contacts = self.wcf.query_sql("MicroMsg.db", "SELECT UserName, NickName, LabelIDList  FROM Contact;")
