### ISSUE TITLE
[💡SUG] 将WeChatFerry/sdk编译为单独的dll动态库

### ISSUE THREAD

**Issue by rehiy** [lich0821/WeChatFerry#84]
**你希望添加的功能是否与某个问题相关？**
启动client时，需要以call的方式行wcf.exe

**描述你希望的解决方案**
将WeChatFerry/sdk编译为单独的dll动态库，允许以dll的方式调用

**Comment by lich0821** [comment]
[v39.0.4](https://github.com/lich0821/WeChatFerry/releases/tag/v39.0.4) 已提供
