### ISSUE TITLE
wcfhttp 增加密钥之类的验证

### ISSUE THREAD

**Issue by wxyShine** [lich0821/WeChatFerry#86]
wcfhttp 启动时--cb 指定地址,  可以增加一个密钥吗   就是调用ip:9999 时需要验证并不是谁都可以调用.  可能服务和 wcfhttp不在一台机器上

**Comment by phil616** [comment]
有一个临时替代的方法，即屏蔽9999的入站端口，然后通过反向代理开放一个其他端口来跳转，但在跳转的时候检查密码，你可以自己搭建一个过滤器。这里有一个非常简单的办法，通过Nginx在反向代理时候的检查来实现密码功能：
`server {
    listen 9998; # 真正开放的端口，但要屏蔽9999
    location / {
        proxy_pass http://0.0.0.0:9999; # wcfhttp的端口
        # 检查 HTTP 头部 'X-Password' 的密码
        if ($http_x_password != "123456") { # 把这个123456换成你的密码
            return 401;
        }
        # 如果密码正确就转发
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}`
如果你想配置更复杂的权限验证，那么建议自己再搭建一个中间的鉴权服务器

**Comment by lich0821** [comment]
> 有一个临时替代的方法，即屏蔽9999的入站端口，然后通过反向代理开放一个其他端口来跳转，但在跳转的时候检查密码，你可以自己搭建一个过滤器。这里有一个非常简单的办法，通过Nginx在反向代理时候的检查来实现密码功能：
> 
> ```
> server {
>     listen 9998; # 真正开放的端口，但要屏蔽9999
>     location / {
>         proxy_pass http://0.0.0.0:9999; # wcfhttp的端口
>         # 检查 HTTP 头部 'X-Password' 的密码
>         if ($http_x_password != "123456") { # 把这个123456换成你的密码
>             return 401;
>         }
>         # 如果密码正确就转发
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> ```
> 
> 如果你想配置更复杂的权限验证，那么建议自己再搭建一个中间的鉴权服务器

如果HTTP传密码安全性不够，可以考虑用[Caddy](https://github.com/caddyserver/caddy)，自动切换HTTPS。

**Comment by rehiy** [comment]
gohttp 客户端已实现
