### ISSUE TITLE
[🐛BUG] 无法正常读取到别人发送消息

### ISSUE THREAD

**Issue by pysoer** [lich0821/WeChatFerry#9]
**描述这个 bug**
对 bug 作一个清晰简明的描述，包括：
使用python下面的demo.py的方式来运行时，出现下面的错误，无法正常读取到别人发送消息。但主动发送（wcf.send_text）是正常的。
Traceback (most recent call last):
  File "D:\111\wechatBot.py", line 57, in process_msg
    msg = wcf.get_msg()
  File "D:\Anaconda3\envs\test\lib\site-packages\wcferry\client.py", line 264, in get_msg
    return self.msgQ.get(block, timeout=1)
  File "D:\Anaconda3\envs\test\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
环境：Python 3.9.16，Windows10 x64

**Comment by pysoer** [comment]
> 新消息会存放在消息队列里，应用通过`get_msg()`去读取（消息队列），默认超时时间是1秒；如果1秒内没有消息，则会报超时异常。这是符合预期的，需要自己处理这个异常。请参考：[demo.py#L14](https://github.com/lich0821/WeChatFerry/blob/master/python/demo.py#L14)。

很感谢您百忙之中的回复，我用这个方式还是不成功，后面用的[https://github.com/lich0821/WeChatRobot/blob/3b20d1de2a3bfca1847aca9118daa52cd46b9853/robot.py#L127](robot.py#L127)的方式成功了。学艺不精，见笑了。

**Comment by pysoer** [comment]
> 客气。[robot.py#L127](https://github.com/lich0821/WeChatFerry/issues/robot.py#L127)也行，是为了兼容旧的接口。不过这方法，在同时有大量消息的过来的时候，存在丢失消息的可能。

实际上最后发现原因是：每次重新打开脚本，都需要退出再重新打开微信，才能正常获取消息，您的两种方式都是正常的。另外发现运行几个小时后，又开始获取不到微信消息了。请问有群可以拉一下不，这里不太方便沟通。

**Comment by lich0821** [comment]
项目首页，有个二维码，就可以找到群了。

**Comment by lich0821** [comment]
先关闭，有问题随时打开。

**Comment by MrChengCun** [comment]
> > 客气。[robot.py#L127](https://github.com/lich0821/WeChatFerry/issues/robot.py#L127)也行，是为了兼容旧的接口。不过这方法，在同时有大量消息的过来的时候，存在丢失消息的可能。
> 
> 实际上最后发现原因是：每次重新打开脚本，都需要退出再重新打开微信，才能正常获取消息，您的两种方式都是正常的。另外发现运行几个小时后，又开始获取不到微信消息了。请问有群可以拉一下不，这里不太方便沟通。

我的问题和他的一模一样，麻烦大佬看看，谢谢了

**Comment by pysoer** [comment]
> > > 客气。[robot.py#L127](https://github.com/lich0821/WeChatFerry/issues/robot.py#L127)也行，是为了兼容旧的接口。不过这方法，在同时有大量消息的过来的时候，存在丢失消息的可能。
> > 
> > 
> > 实际上最后发现原因是：每次重新打开脚本，都需要退出再重新打开微信，才能正常获取消息，您的两种方式都是正常的。另外发现运行几个小时后，又开始获取不到微信消息了。请问有群可以拉一下不，这里不太方便沟通。
> 
> 我的问题和他的一模一样，麻烦大佬看看，谢谢了

别强行退出cmd,按ctrl+c退出。还有加群再提问，这个issues都关闭了。
