### ISSUE TITLE
有附近的人相关功能吗

### ISSUE THREAD

**Issue by tiam-bloom** [lich0821/WeChatFerry#91]
**你希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述你希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述你考虑的替代方案**
关于你考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
你可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by lich0821** [comment]
还有这功能？话说这功能用来干嘛？

**Comment by tiam-bloom** [comment]
还能干嘛, 做营销呗

**Comment by lich0821** [comment]
会玩～可以看看iPad协议，估计支持。

**Comment by tiam-bloom** [comment]
好的, 感谢指路
