### ISSUE TITLE
Codec.lib, LNK2001	无法解析的外部符号 _lame_set_mode

### ISSUE THREAD

**Issue by newsn** [lich0821/WeChatFerry#93]
似乎smc目录下面的Codec.lib，存在着某些缺陷。
现在报错下面的类似信息：

无法解析的外部符号 _lame_set_mode

如图所示：
![codec-error](https://github.com/lich0821/WeChatFerry/assets/3888626/e09f4e90-1225-406c-8503-bd095d7be022)

vs2019，toolset142，不知道该如何继续编译呢？谢谢

**Comment by lich0821** [comment]
```sh
vcpkg install mp3lame:x86-windows-static
```

[参考](https://github.com/lich0821/SilkMp3Converter)
