### ISSUE TITLE
请问如何在python,使用WeChatFerry 发图片,我找不到发图片的命令

### ISSUE THREAD

**Issue by linlaosan3** [lich0821/WeChatFerry#94]
请问如何在python,使用WeChatFerry 发图片,我找不到发图片的命令
谢谢

**Comment by lich0821** [comment]
这是你没读文档，不是BUG。。。

**Comment by lich0821** [comment]
* [WeChatRobot](https://github.com/lich0821/WeChatRobot)
* [文档](https://wechatferry.readthedocs.io/zh/latest/)

**Comment by linlaosan3** [comment]
> * [WeChatRobot](https://github.com/lich0821/WeChatRobot)
> * [文档](https://wechatferry.readthedocs.io/zh/latest/)

Python,你好,我是新手,我真没找到文档,你帮下我吗

**Comment by linlaosan3** [comment]
朋友,你好,我在文档真没找到发图片的命令,你能指点下吗,谢谢
